// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/enum.proto

package wallet // import "gitlab.bull-b.com/aua/aua-proto/wallet"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChainRecordStatus int32

const (
	ChainRecordStatus_ChainRecordStatus_Invalid ChainRecordStatus = 0
	ChainRecordStatus_Ready                     ChainRecordStatus = 1
	ChainRecordStatus_Confirming                ChainRecordStatus = 2
	ChainRecordStatus_Done                      ChainRecordStatus = 3
	ChainRecordStatus_Drop                      ChainRecordStatus = 4
	ChainRecordStatus_Lost                      ChainRecordStatus = 5
	ChainRecordStatus_Pending                   ChainRecordStatus = 6
	ChainRecordStatus_Failure                   ChainRecordStatus = 7
)

var ChainRecordStatus_name = map[int32]string{
	0: "ChainRecordStatus_Invalid",
	1: "Ready",
	2: "Confirming",
	3: "Done",
	4: "Drop",
	5: "Lost",
	6: "Pending",
	7: "Failure",
}
var ChainRecordStatus_value = map[string]int32{
	"ChainRecordStatus_Invalid": 0,
	"Ready":                     1,
	"Confirming":                2,
	"Done":                      3,
	"Drop":                      4,
	"Lost":                      5,
	"Pending":                   6,
	"Failure":                   7,
}

func (x ChainRecordStatus) String() string {
	return proto.EnumName(ChainRecordStatus_name, int32(x))
}
func (ChainRecordStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_c18b5361678bc5cd, []int{0}
}

type ChainDirect int32

const (
	ChainDirect_ChainDirect_In  ChainDirect = 0
	ChainDirect_ChainDirect_Out ChainDirect = 1
)

var ChainDirect_name = map[int32]string{
	0: "ChainDirect_In",
	1: "ChainDirect_Out",
}
var ChainDirect_value = map[string]int32{
	"ChainDirect_In":  0,
	"ChainDirect_Out": 1,
}

func (x ChainDirect) String() string {
	return proto.EnumName(ChainDirect_name, int32(x))
}
func (ChainDirect) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_c18b5361678bc5cd, []int{1}
}

type TransferType int32

const (
	TransferType_TransferType_Invalid TransferType = 0
	TransferType_Issue                TransferType = 1
	TransferType_ApplyIssue           TransferType = 2
	TransferType_Ransomed             TransferType = 3
	TransferType_ContractFee          TransferType = 4
	TransferType_Burn                 TransferType = 5
	TransferType_Transfer             TransferType = 6
)

var TransferType_name = map[int32]string{
	0: "TransferType_Invalid",
	1: "Issue",
	2: "ApplyIssue",
	3: "Ransomed",
	4: "ContractFee",
	5: "Burn",
	6: "Transfer",
}
var TransferType_value = map[string]int32{
	"TransferType_Invalid": 0,
	"Issue":                1,
	"ApplyIssue":           2,
	"Ransomed":             3,
	"ContractFee":          4,
	"Burn":                 5,
	"Transfer":             6,
}

func (x TransferType) String() string {
	return proto.EnumName(TransferType_name, int32(x))
}
func (TransferType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_c18b5361678bc5cd, []int{2}
}

type ChainType int32

const (
	ChainType_ChainType_Invalid ChainType = 0
	ChainType_EOS               ChainType = 1
	ChainType_ETH               ChainType = 2
)

var ChainType_name = map[int32]string{
	0: "ChainType_Invalid",
	1: "EOS",
	2: "ETH",
}
var ChainType_value = map[string]int32{
	"ChainType_Invalid": 0,
	"EOS":               1,
	"ETH":               2,
}

func (x ChainType) String() string {
	return proto.EnumName(ChainType_name, int32(x))
}
func (ChainType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_c18b5361678bc5cd, []int{3}
}

type IssueType int32

const (
	IssueType_IssueType_Invalid IssueType = 0
	IssueType_NormalContract    IssueType = 1
	IssueType_ApplyContract     IssueType = 2
)

var IssueType_name = map[int32]string{
	0: "IssueType_Invalid",
	1: "NormalContract",
	2: "ApplyContract",
}
var IssueType_value = map[string]int32{
	"IssueType_Invalid": 0,
	"NormalContract":    1,
	"ApplyContract":     2,
}

func (x IssueType) String() string {
	return proto.EnumName(IssueType_name, int32(x))
}
func (IssueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_c18b5361678bc5cd, []int{4}
}

func init() {
	proto.RegisterEnum("wallet.ChainRecordStatus", ChainRecordStatus_name, ChainRecordStatus_value)
	proto.RegisterEnum("wallet.ChainDirect", ChainDirect_name, ChainDirect_value)
	proto.RegisterEnum("wallet.TransferType", TransferType_name, TransferType_value)
	proto.RegisterEnum("wallet.ChainType", ChainType_name, ChainType_value)
	proto.RegisterEnum("wallet.IssueType", IssueType_name, IssueType_value)
}

func init() { proto.RegisterFile("wallet/enum.proto", fileDescriptor_enum_c18b5361678bc5cd) }

var fileDescriptor_enum_c18b5361678bc5cd = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4f, 0xe2, 0x40,
	0x14, 0xc6, 0x69, 0x81, 0x02, 0x0f, 0x16, 0x1e, 0xb3, 0xbb, 0xc9, 0xee, 0xc1, 0xab, 0x31, 0x4d,
	0x80, 0x83, 0xc6, 0xbb, 0x80, 0xc4, 0x26, 0x46, 0x0c, 0x70, 0xf2, 0x42, 0xa6, 0xed, 0x80, 0x4d,
	0xa6, 0x33, 0xcd, 0x74, 0x46, 0x83, 0x77, 0xff, 0x6f, 0xd3, 0xa9, 0x90, 0xaa, 0x87, 0x26, 0xdf,
	0xf7, 0xe5, 0xbd, 0x7e, 0xbf, 0xcc, 0x83, 0xe1, 0x2b, 0xe5, 0x9c, 0xe9, 0x09, 0x13, 0x26, 0x1d,
	0x67, 0x4a, 0x6a, 0x49, 0xbc, 0x32, 0xf2, 0xdf, 0x1d, 0x18, 0xce, 0x9e, 0x69, 0x22, 0x56, 0x2c,
	0x92, 0x2a, 0x5e, 0x6b, 0xaa, 0x4d, 0x4e, 0xce, 0xe0, 0xff, 0x8f, 0x70, 0x1b, 0x88, 0x17, 0xca,
	0x93, 0x18, 0x6b, 0xa4, 0x03, 0xcd, 0x15, 0xa3, 0xf1, 0x01, 0x1d, 0xd2, 0x07, 0x98, 0x49, 0xb1,
	0x4b, 0x54, 0x9a, 0x88, 0x3d, 0xba, 0xa4, 0x0d, 0x8d, 0xb9, 0x14, 0x0c, 0xeb, 0x56, 0x29, 0x99,
	0x61, 0xa3, 0x50, 0xf7, 0x32, 0xd7, 0xd8, 0x24, 0x5d, 0x68, 0x3d, 0x32, 0x11, 0x17, 0xa3, 0x5e,
	0x61, 0x16, 0x34, 0xe1, 0x46, 0x31, 0x6c, 0xf9, 0xd7, 0xd0, 0xb5, 0x8d, 0xf3, 0x44, 0xb1, 0x48,
	0x13, 0x02, 0xfd, 0x8a, 0xdd, 0x06, 0x02, 0x6b, 0xe4, 0x37, 0x0c, 0xaa, 0xd9, 0xd2, 0x68, 0x74,
	0xfc, 0x37, 0xe8, 0x6d, 0x14, 0x15, 0xf9, 0x8e, 0xa9, 0xcd, 0x21, 0x63, 0xe4, 0x1f, 0xfc, 0xa9,
	0xfa, 0xaf, 0xd0, 0x41, 0x9e, 0x1b, 0x56, 0x42, 0xdf, 0x64, 0x19, 0x3f, 0x94, 0xde, 0x25, 0x3d,
	0x68, 0xaf, 0xa8, 0xc8, 0x65, 0xca, 0x62, 0xac, 0x93, 0x01, 0x74, 0x67, 0x52, 0x68, 0x45, 0x23,
	0xbd, 0x60, 0xac, 0xe4, 0x9f, 0x1a, 0x25, 0xb0, 0x59, 0x0c, 0x1e, 0xff, 0x8e, 0x9e, 0x7f, 0x05,
	0x1d, 0x0b, 0x64, 0x8b, 0xff, 0x7e, 0xbe, 0xe3, 0xb7, 0xd6, 0x16, 0xd4, 0x6f, 0x97, 0x6b, 0x74,
	0xac, 0xd8, 0xdc, 0xa1, 0xeb, 0x07, 0xd0, 0xb1, 0xbd, 0xc7, 0xad, 0x93, 0xa9, 0x6c, 0x11, 0xe8,
	0x3f, 0x48, 0x95, 0x52, 0x7e, 0x04, 0x41, 0x87, 0x0c, 0xe1, 0x97, 0x85, 0x3e, 0x45, 0xee, 0xf4,
	0xe2, 0xe9, 0x7c, 0x9f, 0x68, 0x4e, 0xc3, 0x71, 0x68, 0x38, 0x1f, 0x85, 0xe3, 0x48, 0xa6, 0x13,
	0x6a, 0x68, 0xf1, 0x8d, 0xec, 0x9d, 0x27, 0xe5, 0x99, 0x43, 0xcf, 0xba, 0xcb, 0x8f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6d, 0xe6, 0xa2, 0x1b, 0x0a, 0x02, 0x00, 0x00,
}
