// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: wallet/enum.proto

/*
Package wallet is a generated protocol buffer package.

It is generated from these files:
	wallet/enum.proto
	wallet/wallet.proto

It has these top-level messages:
	SignedChainRecordReq
	CheckAddressReq
	GetTransferAddressReq
	CreateIssueChainRecordReq
	CreateIssueChainRecordRsp
	CreateBurnChainRecordReq
	CreateBurnChainRecordRsp
	GetTransferAddressRsp
	PageExpectedProfitReq
	PageExpectedProfitResp
	ProfitRecord
	PageChainRecordReq
	PageChainRecordResp
	ChainRecord
	UserWalletInfo
	GetSupplyReq
	GetSupplyRsp
	GetAccountBalanceReq
	GetAccountBalanceRsp
*/
package wallet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
