// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/wallet.proto

package wallet // import "gitlab.bull-b.com/aua/aua-proto/wallet"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "gitlab.bull-b.com/aua/aua-proto/common"
import _ "gitlab.bull-b.com/aua/aua-proto/user"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignedChainRecordReq struct {
	ChainRecordID        uint64   `protobuf:"varint,1,opt,name=ChainRecordID,proto3" json:"ChainRecordID,omitempty"`
	SignedTransaction    string   `protobuf:"bytes,2,opt,name=SignedTransaction,proto3" json:"SignedTransaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedChainRecordReq) Reset()         { *m = SignedChainRecordReq{} }
func (m *SignedChainRecordReq) String() string { return proto.CompactTextString(m) }
func (*SignedChainRecordReq) ProtoMessage()    {}
func (*SignedChainRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{0}
}
func (m *SignedChainRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedChainRecordReq.Unmarshal(m, b)
}
func (m *SignedChainRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedChainRecordReq.Marshal(b, m, deterministic)
}
func (dst *SignedChainRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedChainRecordReq.Merge(dst, src)
}
func (m *SignedChainRecordReq) XXX_Size() int {
	return xxx_messageInfo_SignedChainRecordReq.Size(m)
}
func (m *SignedChainRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedChainRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignedChainRecordReq proto.InternalMessageInfo

func (m *SignedChainRecordReq) GetChainRecordID() uint64 {
	if m != nil {
		return m.ChainRecordID
	}
	return 0
}

func (m *SignedChainRecordReq) GetSignedTransaction() string {
	if m != nil {
		return m.SignedTransaction
	}
	return ""
}

// 检查链上地址请求
type CheckAddressReq struct {
	ChainType            ChainType `protobuf:"varint,1,opt,name=ChainType,proto3,enum=wallet.ChainType" json:"ChainType,omitempty"`
	Address              string    `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckAddressReq) Reset()         { *m = CheckAddressReq{} }
func (m *CheckAddressReq) String() string { return proto.CompactTextString(m) }
func (*CheckAddressReq) ProtoMessage()    {}
func (*CheckAddressReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{1}
}
func (m *CheckAddressReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAddressReq.Unmarshal(m, b)
}
func (m *CheckAddressReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAddressReq.Marshal(b, m, deterministic)
}
func (dst *CheckAddressReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAddressReq.Merge(dst, src)
}
func (m *CheckAddressReq) XXX_Size() int {
	return xxx_messageInfo_CheckAddressReq.Size(m)
}
func (m *CheckAddressReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAddressReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAddressReq proto.InternalMessageInfo

func (m *CheckAddressReq) GetChainType() ChainType {
	if m != nil {
		return m.ChainType
	}
	return ChainType_ChainType_Invalid
}

func (m *CheckAddressReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetTransferAddressReq struct {
	ChainType            ChainType    `protobuf:"varint,1,opt,name=ChainType,proto3,enum=wallet.ChainType" json:"ChainType,omitempty"`
	TransferType         TransferType `protobuf:"varint,2,opt,name=TransferType,proto3,enum=wallet.TransferType" json:"TransferType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTransferAddressReq) Reset()         { *m = GetTransferAddressReq{} }
func (m *GetTransferAddressReq) String() string { return proto.CompactTextString(m) }
func (*GetTransferAddressReq) ProtoMessage()    {}
func (*GetTransferAddressReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{2}
}
func (m *GetTransferAddressReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransferAddressReq.Unmarshal(m, b)
}
func (m *GetTransferAddressReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransferAddressReq.Marshal(b, m, deterministic)
}
func (dst *GetTransferAddressReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransferAddressReq.Merge(dst, src)
}
func (m *GetTransferAddressReq) XXX_Size() int {
	return xxx_messageInfo_GetTransferAddressReq.Size(m)
}
func (m *GetTransferAddressReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransferAddressReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransferAddressReq proto.InternalMessageInfo

func (m *GetTransferAddressReq) GetChainType() ChainType {
	if m != nil {
		return m.ChainType
	}
	return ChainType_ChainType_Invalid
}

func (m *GetTransferAddressReq) GetTransferType() TransferType {
	if m != nil {
		return m.TransferType
	}
	return TransferType_TransferType_Invalid
}

type CreateIssueChainRecordReq struct {
	ChainType            ChainType `protobuf:"varint,1,opt,name=ChainType,proto3,enum=wallet.ChainType" json:"ChainType,omitempty"`
	Amount               uint64    `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	RelateID             uint64    `protobuf:"varint,3,opt,name=RelateID,proto3" json:"RelateID,omitempty"`
	To                   string    `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
	IssueType            IssueType `protobuf:"varint,5,opt,name=IssueType,proto3,enum=wallet.IssueType" json:"IssueType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateIssueChainRecordReq) Reset()         { *m = CreateIssueChainRecordReq{} }
func (m *CreateIssueChainRecordReq) String() string { return proto.CompactTextString(m) }
func (*CreateIssueChainRecordReq) ProtoMessage()    {}
func (*CreateIssueChainRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{3}
}
func (m *CreateIssueChainRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIssueChainRecordReq.Unmarshal(m, b)
}
func (m *CreateIssueChainRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIssueChainRecordReq.Marshal(b, m, deterministic)
}
func (dst *CreateIssueChainRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIssueChainRecordReq.Merge(dst, src)
}
func (m *CreateIssueChainRecordReq) XXX_Size() int {
	return xxx_messageInfo_CreateIssueChainRecordReq.Size(m)
}
func (m *CreateIssueChainRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIssueChainRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIssueChainRecordReq proto.InternalMessageInfo

func (m *CreateIssueChainRecordReq) GetChainType() ChainType {
	if m != nil {
		return m.ChainType
	}
	return ChainType_ChainType_Invalid
}

func (m *CreateIssueChainRecordReq) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateIssueChainRecordReq) GetRelateID() uint64 {
	if m != nil {
		return m.RelateID
	}
	return 0
}

func (m *CreateIssueChainRecordReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CreateIssueChainRecordReq) GetIssueType() IssueType {
	if m != nil {
		return m.IssueType
	}
	return IssueType_IssueType_Invalid
}

type CreateIssueChainRecordRsp struct {
	ChainRecordID        uint64   `protobuf:"varint,1,opt,name=ChainRecordID,proto3" json:"ChainRecordID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIssueChainRecordRsp) Reset()         { *m = CreateIssueChainRecordRsp{} }
func (m *CreateIssueChainRecordRsp) String() string { return proto.CompactTextString(m) }
func (*CreateIssueChainRecordRsp) ProtoMessage()    {}
func (*CreateIssueChainRecordRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{4}
}
func (m *CreateIssueChainRecordRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIssueChainRecordRsp.Unmarshal(m, b)
}
func (m *CreateIssueChainRecordRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIssueChainRecordRsp.Marshal(b, m, deterministic)
}
func (dst *CreateIssueChainRecordRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIssueChainRecordRsp.Merge(dst, src)
}
func (m *CreateIssueChainRecordRsp) XXX_Size() int {
	return xxx_messageInfo_CreateIssueChainRecordRsp.Size(m)
}
func (m *CreateIssueChainRecordRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIssueChainRecordRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIssueChainRecordRsp proto.InternalMessageInfo

func (m *CreateIssueChainRecordRsp) GetChainRecordID() uint64 {
	if m != nil {
		return m.ChainRecordID
	}
	return 0
}

type CreateBurnChainRecordReq struct {
	ChainRecordID        uint64   `protobuf:"varint,1,opt,name=ChainRecordID,proto3" json:"ChainRecordID,omitempty"`
	SignedTransaction    string   `protobuf:"bytes,2,opt,name=SignedTransaction,proto3" json:"SignedTransaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBurnChainRecordReq) Reset()         { *m = CreateBurnChainRecordReq{} }
func (m *CreateBurnChainRecordReq) String() string { return proto.CompactTextString(m) }
func (*CreateBurnChainRecordReq) ProtoMessage()    {}
func (*CreateBurnChainRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{5}
}
func (m *CreateBurnChainRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBurnChainRecordReq.Unmarshal(m, b)
}
func (m *CreateBurnChainRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBurnChainRecordReq.Marshal(b, m, deterministic)
}
func (dst *CreateBurnChainRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBurnChainRecordReq.Merge(dst, src)
}
func (m *CreateBurnChainRecordReq) XXX_Size() int {
	return xxx_messageInfo_CreateBurnChainRecordReq.Size(m)
}
func (m *CreateBurnChainRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBurnChainRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBurnChainRecordReq proto.InternalMessageInfo

func (m *CreateBurnChainRecordReq) GetChainRecordID() uint64 {
	if m != nil {
		return m.ChainRecordID
	}
	return 0
}

func (m *CreateBurnChainRecordReq) GetSignedTransaction() string {
	if m != nil {
		return m.SignedTransaction
	}
	return ""
}

type CreateBurnChainRecordRsp struct {
	ChainRecordID        uint64   `protobuf:"varint,1,opt,name=ChainRecordID,proto3" json:"ChainRecordID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBurnChainRecordRsp) Reset()         { *m = CreateBurnChainRecordRsp{} }
func (m *CreateBurnChainRecordRsp) String() string { return proto.CompactTextString(m) }
func (*CreateBurnChainRecordRsp) ProtoMessage()    {}
func (*CreateBurnChainRecordRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{6}
}
func (m *CreateBurnChainRecordRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBurnChainRecordRsp.Unmarshal(m, b)
}
func (m *CreateBurnChainRecordRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBurnChainRecordRsp.Marshal(b, m, deterministic)
}
func (dst *CreateBurnChainRecordRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBurnChainRecordRsp.Merge(dst, src)
}
func (m *CreateBurnChainRecordRsp) XXX_Size() int {
	return xxx_messageInfo_CreateBurnChainRecordRsp.Size(m)
}
func (m *CreateBurnChainRecordRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBurnChainRecordRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBurnChainRecordRsp proto.InternalMessageInfo

func (m *CreateBurnChainRecordRsp) GetChainRecordID() uint64 {
	if m != nil {
		return m.ChainRecordID
	}
	return 0
}

type GetTransferAddressRsp struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransferAddressRsp) Reset()         { *m = GetTransferAddressRsp{} }
func (m *GetTransferAddressRsp) String() string { return proto.CompactTextString(m) }
func (*GetTransferAddressRsp) ProtoMessage()    {}
func (*GetTransferAddressRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{7}
}
func (m *GetTransferAddressRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransferAddressRsp.Unmarshal(m, b)
}
func (m *GetTransferAddressRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransferAddressRsp.Marshal(b, m, deterministic)
}
func (dst *GetTransferAddressRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransferAddressRsp.Merge(dst, src)
}
func (m *GetTransferAddressRsp) XXX_Size() int {
	return xxx_messageInfo_GetTransferAddressRsp.Size(m)
}
func (m *GetTransferAddressRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransferAddressRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransferAddressRsp proto.InternalMessageInfo

func (m *GetTransferAddressRsp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// 获取总收益时，合约和日期不用填
type PageExpectedProfitReq struct {
	Page                 *common.PageReq              `protobuf:"bytes,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Conditions           *PageExpectedProfitReq_Query `protobuf:"bytes,2,opt,name=Conditions,proto3" json:"Conditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *PageExpectedProfitReq) Reset()         { *m = PageExpectedProfitReq{} }
func (m *PageExpectedProfitReq) String() string { return proto.CompactTextString(m) }
func (*PageExpectedProfitReq) ProtoMessage()    {}
func (*PageExpectedProfitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{8}
}
func (m *PageExpectedProfitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageExpectedProfitReq.Unmarshal(m, b)
}
func (m *PageExpectedProfitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageExpectedProfitReq.Marshal(b, m, deterministic)
}
func (dst *PageExpectedProfitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageExpectedProfitReq.Merge(dst, src)
}
func (m *PageExpectedProfitReq) XXX_Size() int {
	return xxx_messageInfo_PageExpectedProfitReq.Size(m)
}
func (m *PageExpectedProfitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PageExpectedProfitReq.DiscardUnknown(m)
}

var xxx_messageInfo_PageExpectedProfitReq proto.InternalMessageInfo

func (m *PageExpectedProfitReq) GetPage() *common.PageReq {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *PageExpectedProfitReq) GetConditions() *PageExpectedProfitReq_Query {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type PageExpectedProfitReq_Query struct {
	ContractID           uint64   `protobuf:"varint,1,opt,name=ContractID,proto3" json:"ContractID,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=Date,proto3" json:"Date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageExpectedProfitReq_Query) Reset()         { *m = PageExpectedProfitReq_Query{} }
func (m *PageExpectedProfitReq_Query) String() string { return proto.CompactTextString(m) }
func (*PageExpectedProfitReq_Query) ProtoMessage()    {}
func (*PageExpectedProfitReq_Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{8, 0}
}
func (m *PageExpectedProfitReq_Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageExpectedProfitReq_Query.Unmarshal(m, b)
}
func (m *PageExpectedProfitReq_Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageExpectedProfitReq_Query.Marshal(b, m, deterministic)
}
func (dst *PageExpectedProfitReq_Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageExpectedProfitReq_Query.Merge(dst, src)
}
func (m *PageExpectedProfitReq_Query) XXX_Size() int {
	return xxx_messageInfo_PageExpectedProfitReq_Query.Size(m)
}
func (m *PageExpectedProfitReq_Query) XXX_DiscardUnknown() {
	xxx_messageInfo_PageExpectedProfitReq_Query.DiscardUnknown(m)
}

var xxx_messageInfo_PageExpectedProfitReq_Query proto.InternalMessageInfo

func (m *PageExpectedProfitReq_Query) GetContractID() uint64 {
	if m != nil {
		return m.ContractID
	}
	return 0
}

func (m *PageExpectedProfitReq_Query) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type PageExpectedProfitResp struct {
	Count                uint64          `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	TotalAmount          uint64          `protobuf:"varint,2,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	Data                 []*ProfitRecord `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PageExpectedProfitResp) Reset()         { *m = PageExpectedProfitResp{} }
func (m *PageExpectedProfitResp) String() string { return proto.CompactTextString(m) }
func (*PageExpectedProfitResp) ProtoMessage()    {}
func (*PageExpectedProfitResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{9}
}
func (m *PageExpectedProfitResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageExpectedProfitResp.Unmarshal(m, b)
}
func (m *PageExpectedProfitResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageExpectedProfitResp.Marshal(b, m, deterministic)
}
func (dst *PageExpectedProfitResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageExpectedProfitResp.Merge(dst, src)
}
func (m *PageExpectedProfitResp) XXX_Size() int {
	return xxx_messageInfo_PageExpectedProfitResp.Size(m)
}
func (m *PageExpectedProfitResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PageExpectedProfitResp.DiscardUnknown(m)
}

var xxx_messageInfo_PageExpectedProfitResp proto.InternalMessageInfo

func (m *PageExpectedProfitResp) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PageExpectedProfitResp) GetTotalAmount() uint64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *PageExpectedProfitResp) GetData() []*ProfitRecord {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProfitRecord struct {
	ContractID           uint64   `protobuf:"varint,1,opt,name=ContractID,proto3" json:"ContractID,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=Date,proto3" json:"Date,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfitRecord) Reset()         { *m = ProfitRecord{} }
func (m *ProfitRecord) String() string { return proto.CompactTextString(m) }
func (*ProfitRecord) ProtoMessage()    {}
func (*ProfitRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{10}
}
func (m *ProfitRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfitRecord.Unmarshal(m, b)
}
func (m *ProfitRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfitRecord.Marshal(b, m, deterministic)
}
func (dst *ProfitRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfitRecord.Merge(dst, src)
}
func (m *ProfitRecord) XXX_Size() int {
	return xxx_messageInfo_ProfitRecord.Size(m)
}
func (m *ProfitRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfitRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ProfitRecord proto.InternalMessageInfo

func (m *ProfitRecord) GetContractID() uint64 {
	if m != nil {
		return m.ContractID
	}
	return 0
}

func (m *ProfitRecord) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ProfitRecord) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type PageChainRecordReq struct {
	Page                 *common.PageReq           `protobuf:"bytes,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Conditions           *PageChainRecordReq_Query `protobuf:"bytes,2,opt,name=Conditions,proto3" json:"Conditions,omitempty"`
	Report               bool                      `protobuf:"varint,3,opt,name=Report,proto3" json:"Report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PageChainRecordReq) Reset()         { *m = PageChainRecordReq{} }
func (m *PageChainRecordReq) String() string { return proto.CompactTextString(m) }
func (*PageChainRecordReq) ProtoMessage()    {}
func (*PageChainRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{11}
}
func (m *PageChainRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageChainRecordReq.Unmarshal(m, b)
}
func (m *PageChainRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageChainRecordReq.Marshal(b, m, deterministic)
}
func (dst *PageChainRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageChainRecordReq.Merge(dst, src)
}
func (m *PageChainRecordReq) XXX_Size() int {
	return xxx_messageInfo_PageChainRecordReq.Size(m)
}
func (m *PageChainRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PageChainRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_PageChainRecordReq proto.InternalMessageInfo

func (m *PageChainRecordReq) GetPage() *common.PageReq {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *PageChainRecordReq) GetConditions() *PageChainRecordReq_Query {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *PageChainRecordReq) GetReport() bool {
	if m != nil {
		return m.Report
	}
	return false
}

type PageChainRecordReq_Query struct {
	Status               ChainRecordStatus   `protobuf:"varint,1,opt,name=Status,proto3,enum=wallet.ChainRecordStatus" json:"Status,omitempty"`
	RelatedType          common.BusinessType `protobuf:"varint,2,opt,name=RelatedType,proto3,enum=common.BusinessType" json:"RelatedType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PageChainRecordReq_Query) Reset()         { *m = PageChainRecordReq_Query{} }
func (m *PageChainRecordReq_Query) String() string { return proto.CompactTextString(m) }
func (*PageChainRecordReq_Query) ProtoMessage()    {}
func (*PageChainRecordReq_Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{11, 0}
}
func (m *PageChainRecordReq_Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageChainRecordReq_Query.Unmarshal(m, b)
}
func (m *PageChainRecordReq_Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageChainRecordReq_Query.Marshal(b, m, deterministic)
}
func (dst *PageChainRecordReq_Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageChainRecordReq_Query.Merge(dst, src)
}
func (m *PageChainRecordReq_Query) XXX_Size() int {
	return xxx_messageInfo_PageChainRecordReq_Query.Size(m)
}
func (m *PageChainRecordReq_Query) XXX_DiscardUnknown() {
	xxx_messageInfo_PageChainRecordReq_Query.DiscardUnknown(m)
}

var xxx_messageInfo_PageChainRecordReq_Query proto.InternalMessageInfo

func (m *PageChainRecordReq_Query) GetStatus() ChainRecordStatus {
	if m != nil {
		return m.Status
	}
	return ChainRecordStatus_ChainRecordStatus_Invalid
}

func (m *PageChainRecordReq_Query) GetRelatedType() common.BusinessType {
	if m != nil {
		return m.RelatedType
	}
	return common.BusinessType_Invalid
}

type PageChainRecordResp struct {
	Count                uint64         `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Data                 []*ChainRecord `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	ReportUrl            string         `protobuf:"bytes,3,opt,name=ReportUrl,proto3" json:"ReportUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PageChainRecordResp) Reset()         { *m = PageChainRecordResp{} }
func (m *PageChainRecordResp) String() string { return proto.CompactTextString(m) }
func (*PageChainRecordResp) ProtoMessage()    {}
func (*PageChainRecordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{12}
}
func (m *PageChainRecordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageChainRecordResp.Unmarshal(m, b)
}
func (m *PageChainRecordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageChainRecordResp.Marshal(b, m, deterministic)
}
func (dst *PageChainRecordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageChainRecordResp.Merge(dst, src)
}
func (m *PageChainRecordResp) XXX_Size() int {
	return xxx_messageInfo_PageChainRecordResp.Size(m)
}
func (m *PageChainRecordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PageChainRecordResp.DiscardUnknown(m)
}

var xxx_messageInfo_PageChainRecordResp proto.InternalMessageInfo

func (m *PageChainRecordResp) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PageChainRecordResp) GetData() []*ChainRecord {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PageChainRecordResp) GetReportUrl() string {
	if m != nil {
		return m.ReportUrl
	}
	return ""
}

type ChainRecord struct {
	ChainRecordID        uint64              `protobuf:"varint,1,opt,name=ChainRecordID,proto3" json:"ChainRecordID,omitempty"`
	Symbol               string              `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	BlockChain           string              `protobuf:"bytes,3,opt,name=BlockChain,proto3" json:"BlockChain,omitempty"`
	From                 string              `protobuf:"bytes,4,opt,name=From,proto3" json:"From,omitempty"`
	To                   string              `protobuf:"bytes,5,opt,name=To,proto3" json:"To,omitempty"`
	Amount               uint64              `protobuf:"varint,6,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Memo                 string              `protobuf:"bytes,7,opt,name=Memo,proto3" json:"Memo,omitempty"`
	Status               ChainRecordStatus   `protobuf:"varint,8,opt,name=Status,proto3,enum=wallet.ChainRecordStatus" json:"Status,omitempty"`
	RelatedID            uint64              `protobuf:"varint,9,opt,name=RelatedID,proto3" json:"RelatedID,omitempty"`
	RelatedType          common.BusinessType `protobuf:"varint,10,opt,name=RelatedType,proto3,enum=common.BusinessType" json:"RelatedType,omitempty"`
	TransactionID        string              `protobuf:"bytes,11,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	UserID               uint64              `protobuf:"varint,12,opt,name=UserID,proto3" json:"UserID,omitempty"`
	User                 *UserWalletInfo     `protobuf:"bytes,13,opt,name=User,proto3" json:"User,omitempty"`
	ReceivedAmount       uint64              `protobuf:"varint,14,opt,name=ReceivedAmount,proto3" json:"ReceivedAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ChainRecord) Reset()         { *m = ChainRecord{} }
func (m *ChainRecord) String() string { return proto.CompactTextString(m) }
func (*ChainRecord) ProtoMessage()    {}
func (*ChainRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{13}
}
func (m *ChainRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainRecord.Unmarshal(m, b)
}
func (m *ChainRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainRecord.Marshal(b, m, deterministic)
}
func (dst *ChainRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainRecord.Merge(dst, src)
}
func (m *ChainRecord) XXX_Size() int {
	return xxx_messageInfo_ChainRecord.Size(m)
}
func (m *ChainRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ChainRecord proto.InternalMessageInfo

func (m *ChainRecord) GetChainRecordID() uint64 {
	if m != nil {
		return m.ChainRecordID
	}
	return 0
}

func (m *ChainRecord) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ChainRecord) GetBlockChain() string {
	if m != nil {
		return m.BlockChain
	}
	return ""
}

func (m *ChainRecord) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ChainRecord) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ChainRecord) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChainRecord) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *ChainRecord) GetStatus() ChainRecordStatus {
	if m != nil {
		return m.Status
	}
	return ChainRecordStatus_ChainRecordStatus_Invalid
}

func (m *ChainRecord) GetRelatedID() uint64 {
	if m != nil {
		return m.RelatedID
	}
	return 0
}

func (m *ChainRecord) GetRelatedType() common.BusinessType {
	if m != nil {
		return m.RelatedType
	}
	return common.BusinessType_Invalid
}

func (m *ChainRecord) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *ChainRecord) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *ChainRecord) GetUser() *UserWalletInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChainRecord) GetReceivedAmount() uint64 {
	if m != nil {
		return m.ReceivedAmount
	}
	return 0
}

type UserWalletInfo struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	RealName             string   `protobuf:"bytes,2,opt,name=RealName,proto3" json:"RealName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserWalletInfo) Reset()         { *m = UserWalletInfo{} }
func (m *UserWalletInfo) String() string { return proto.CompactTextString(m) }
func (*UserWalletInfo) ProtoMessage()    {}
func (*UserWalletInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{14}
}
func (m *UserWalletInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWalletInfo.Unmarshal(m, b)
}
func (m *UserWalletInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWalletInfo.Marshal(b, m, deterministic)
}
func (dst *UserWalletInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWalletInfo.Merge(dst, src)
}
func (m *UserWalletInfo) XXX_Size() int {
	return xxx_messageInfo_UserWalletInfo.Size(m)
}
func (m *UserWalletInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWalletInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserWalletInfo proto.InternalMessageInfo

func (m *UserWalletInfo) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserWalletInfo) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

type GetSupplyReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSupplyReq) Reset()         { *m = GetSupplyReq{} }
func (m *GetSupplyReq) String() string { return proto.CompactTextString(m) }
func (*GetSupplyReq) ProtoMessage()    {}
func (*GetSupplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{15}
}
func (m *GetSupplyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSupplyReq.Unmarshal(m, b)
}
func (m *GetSupplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSupplyReq.Marshal(b, m, deterministic)
}
func (dst *GetSupplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSupplyReq.Merge(dst, src)
}
func (m *GetSupplyReq) XXX_Size() int {
	return xxx_messageInfo_GetSupplyReq.Size(m)
}
func (m *GetSupplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSupplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSupplyReq proto.InternalMessageInfo

func (m *GetSupplyReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetSupplyReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type GetSupplyRsp struct {
	Supply               uint64   `protobuf:"varint,1,opt,name=Supply,proto3" json:"Supply,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSupplyRsp) Reset()         { *m = GetSupplyRsp{} }
func (m *GetSupplyRsp) String() string { return proto.CompactTextString(m) }
func (*GetSupplyRsp) ProtoMessage()    {}
func (*GetSupplyRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{16}
}
func (m *GetSupplyRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSupplyRsp.Unmarshal(m, b)
}
func (m *GetSupplyRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSupplyRsp.Marshal(b, m, deterministic)
}
func (dst *GetSupplyRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSupplyRsp.Merge(dst, src)
}
func (m *GetSupplyRsp) XXX_Size() int {
	return xxx_messageInfo_GetSupplyRsp.Size(m)
}
func (m *GetSupplyRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSupplyRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSupplyRsp proto.InternalMessageInfo

func (m *GetSupplyRsp) GetSupply() uint64 {
	if m != nil {
		return m.Supply
	}
	return 0
}

func (m *GetSupplyRsp) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type GetAccountBalanceReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountBalanceReq) Reset()         { *m = GetAccountBalanceReq{} }
func (m *GetAccountBalanceReq) String() string { return proto.CompactTextString(m) }
func (*GetAccountBalanceReq) ProtoMessage()    {}
func (*GetAccountBalanceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{17}
}
func (m *GetAccountBalanceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountBalanceReq.Unmarshal(m, b)
}
func (m *GetAccountBalanceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountBalanceReq.Marshal(b, m, deterministic)
}
func (dst *GetAccountBalanceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountBalanceReq.Merge(dst, src)
}
func (m *GetAccountBalanceReq) XXX_Size() int {
	return xxx_messageInfo_GetAccountBalanceReq.Size(m)
}
func (m *GetAccountBalanceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountBalanceReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountBalanceReq proto.InternalMessageInfo

func (m *GetAccountBalanceReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type GetAccountBalanceRsp struct {
	Quantity             string   `protobuf:"bytes,1,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountBalanceRsp) Reset()         { *m = GetAccountBalanceRsp{} }
func (m *GetAccountBalanceRsp) String() string { return proto.CompactTextString(m) }
func (*GetAccountBalanceRsp) ProtoMessage()    {}
func (*GetAccountBalanceRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_4f6aa8ced82018af, []int{18}
}
func (m *GetAccountBalanceRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountBalanceRsp.Unmarshal(m, b)
}
func (m *GetAccountBalanceRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountBalanceRsp.Marshal(b, m, deterministic)
}
func (dst *GetAccountBalanceRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountBalanceRsp.Merge(dst, src)
}
func (m *GetAccountBalanceRsp) XXX_Size() int {
	return xxx_messageInfo_GetAccountBalanceRsp.Size(m)
}
func (m *GetAccountBalanceRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountBalanceRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountBalanceRsp proto.InternalMessageInfo

func (m *GetAccountBalanceRsp) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func init() {
	proto.RegisterType((*SignedChainRecordReq)(nil), "wallet.SignedChainRecordReq")
	proto.RegisterType((*CheckAddressReq)(nil), "wallet.CheckAddressReq")
	proto.RegisterType((*GetTransferAddressReq)(nil), "wallet.GetTransferAddressReq")
	proto.RegisterType((*CreateIssueChainRecordReq)(nil), "wallet.CreateIssueChainRecordReq")
	proto.RegisterType((*CreateIssueChainRecordRsp)(nil), "wallet.CreateIssueChainRecordRsp")
	proto.RegisterType((*CreateBurnChainRecordReq)(nil), "wallet.CreateBurnChainRecordReq")
	proto.RegisterType((*CreateBurnChainRecordRsp)(nil), "wallet.CreateBurnChainRecordRsp")
	proto.RegisterType((*GetTransferAddressRsp)(nil), "wallet.GetTransferAddressRsp")
	proto.RegisterType((*PageExpectedProfitReq)(nil), "wallet.PageExpectedProfitReq")
	proto.RegisterType((*PageExpectedProfitReq_Query)(nil), "wallet.PageExpectedProfitReq.Query")
	proto.RegisterType((*PageExpectedProfitResp)(nil), "wallet.PageExpectedProfitResp")
	proto.RegisterType((*ProfitRecord)(nil), "wallet.ProfitRecord")
	proto.RegisterType((*PageChainRecordReq)(nil), "wallet.PageChainRecordReq")
	proto.RegisterType((*PageChainRecordReq_Query)(nil), "wallet.PageChainRecordReq.Query")
	proto.RegisterType((*PageChainRecordResp)(nil), "wallet.PageChainRecordResp")
	proto.RegisterType((*ChainRecord)(nil), "wallet.ChainRecord")
	proto.RegisterType((*UserWalletInfo)(nil), "wallet.UserWalletInfo")
	proto.RegisterType((*GetSupplyReq)(nil), "wallet.GetSupplyReq")
	proto.RegisterType((*GetSupplyRsp)(nil), "wallet.GetSupplyRsp")
	proto.RegisterType((*GetAccountBalanceReq)(nil), "wallet.GetAccountBalanceReq")
	proto.RegisterType((*GetAccountBalanceRsp)(nil), "wallet.GetAccountBalanceRsp")
}

func init() { proto.RegisterFile("wallet/wallet.proto", fileDescriptor_wallet_4f6aa8ced82018af) }

var fileDescriptor_wallet_4f6aa8ced82018af = []byte{
	// 1082 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x17, 0x6d, 0x6f, 0xdb, 0xc4,
	0x5f, 0x49, 0xd3, 0xb4, 0xf9, 0xa5, 0x4d, 0xd4, 0x6b, 0x9a, 0xbf, 0xe7, 0xff, 0x98, 0x82, 0x87,
	0x46, 0x84, 0x58, 0xca, 0x82, 0x34, 0x90, 0x90, 0xa6, 0x36, 0xc9, 0x56, 0x05, 0x09, 0xe8, 0x2e,
	0x99, 0x90, 0x06, 0x42, 0x72, 0x9c, 0x6b, 0x67, 0xe6, 0xd8, 0x9e, 0xef, 0x0c, 0x84, 0x97, 0xbc,
	0xe1, 0x5b, 0x21, 0xf1, 0x25, 0xf8, 0x10, 0x7c, 0x0a, 0x74, 0x0f, 0x76, 0xce, 0xb1, 0xd3, 0x65,
	0x45, 0xe2, 0x45, 0x9b, 0xfb, 0x3d, 0x3f, 0xff, 0xee, 0x0c, 0xc7, 0x3f, 0xdb, 0x9e, 0x47, 0xd8,
	0xa9, 0xfc, 0xe9, 0x85, 0x51, 0xc0, 0x02, 0x54, 0x95, 0x90, 0x79, 0xec, 0x04, 0x8b, 0x45, 0xe0,
	0x9f, 0xca, 0x1f, 0x49, 0x34, 0x8f, 0x94, 0x04, 0xf1, 0xe3, 0x45, 0x82, 0x52, 0x7c, 0x1a, 0xaa,
	0x19, 0x53, 0x12, 0xe5, 0x11, 0xfc, 0x9f, 0x44, 0x58, 0x3f, 0x42, 0x6b, 0xe2, 0x5e, 0xfb, 0x64,
	0x3e, 0x7c, 0x65, 0xbb, 0x3e, 0x26, 0x4e, 0x10, 0xcd, 0x31, 0x79, 0x83, 0x3e, 0x80, 0x43, 0x0d,
	0x33, 0x1e, 0x19, 0xa5, 0x4e, 0xa9, 0x5b, 0xc1, 0x59, 0x24, 0xfa, 0x18, 0x8e, 0xa4, 0xf4, 0x34,
	0xb2, 0x7d, 0x6a, 0x3b, 0xcc, 0x0d, 0x7c, 0xa3, 0xdc, 0x29, 0x75, 0x6b, 0x38, 0x4f, 0xb0, 0xbe,
	0x87, 0xe6, 0xf0, 0x15, 0x71, 0x5e, 0x9f, 0xcf, 0xe7, 0x11, 0xa1, 0x94, 0x9b, 0x39, 0x85, 0x9a,
	0xd0, 0x38, 0x5d, 0x86, 0x44, 0x98, 0x68, 0xf4, 0x8f, 0x7a, 0x2a, 0x0b, 0x29, 0x01, 0xaf, 0x78,
	0x90, 0x01, 0x7b, 0x4a, 0x5c, 0xd9, 0x49, 0x40, 0xeb, 0xb7, 0x12, 0x9c, 0x5c, 0x10, 0x26, 0x0c,
	0x5e, 0x91, 0xe8, 0xdf, 0x18, 0xf9, 0x1c, 0x0e, 0x12, 0x35, 0x42, 0xa6, 0x2c, 0x64, 0x5a, 0x89,
	0x8c, 0x4e, 0xc3, 0x19, 0x4e, 0xeb, 0xcf, 0x12, 0xdc, 0x19, 0x46, 0xc4, 0x66, 0x64, 0x4c, 0x69,
	0x4c, 0xd6, 0x92, 0xfa, 0xce, 0x8e, 0xb4, 0xa1, 0x7a, 0xbe, 0x08, 0x62, 0x9f, 0x09, 0x17, 0x2a,
	0x58, 0x41, 0xc8, 0x84, 0x7d, 0x4c, 0x3c, 0x6e, 0x65, 0x64, 0xec, 0x08, 0x4a, 0x0a, 0xa3, 0x06,
	0x94, 0xa7, 0x81, 0x51, 0x11, 0xc9, 0x29, 0x4f, 0x03, 0x6e, 0x54, 0xf8, 0x22, 0x8c, 0xee, 0x66,
	0x8d, 0xa6, 0x04, 0xbc, 0xe2, 0xb1, 0xce, 0x37, 0x86, 0x40, 0xc3, 0xed, 0xfa, 0xc2, 0xf2, 0xc1,
	0x90, 0x2a, 0x06, 0x71, 0xe4, 0xff, 0x07, 0x9d, 0x75, 0xb6, 0xc9, 0xde, 0xd6, 0x1e, 0x3f, 0x2a,
	0x6c, 0x1e, 0x1a, 0xea, 0x0d, 0x57, 0xca, 0x36, 0xdc, 0x1f, 0x25, 0x38, 0xb9, 0xb4, 0xaf, 0xc9,
	0xd3, 0x5f, 0x42, 0xe2, 0x30, 0x32, 0xbf, 0x8c, 0x82, 0x2b, 0x97, 0xf1, 0x10, 0xef, 0x43, 0x85,
	0x13, 0x84, 0x40, 0xbd, 0xdf, 0xec, 0xa9, 0xc9, 0xe5, 0x38, 0x4c, 0xde, 0x60, 0x41, 0x44, 0x43,
	0x80, 0x61, 0xe0, 0xcf, 0x5d, 0x1e, 0x80, 0x6c, 0xe6, 0x7a, 0xff, 0x7e, 0x52, 0x98, 0x42, 0xbd,
	0xbd, 0xe7, 0x31, 0x89, 0x96, 0x58, 0x13, 0x33, 0xbf, 0x80, 0x5d, 0x81, 0x44, 0xf7, 0x84, 0x36,
	0x16, 0xd9, 0x0e, 0x4b, 0x43, 0xd4, 0x30, 0x08, 0x41, 0x65, 0x64, 0x33, 0xa2, 0x52, 0x28, 0xce,
	0xd6, 0xaf, 0xd0, 0x2e, 0xb2, 0x43, 0x43, 0xd4, 0x82, 0xdd, 0xa1, 0x68, 0x3b, 0xa9, 0x48, 0x02,
	0xa8, 0x03, 0xf5, 0x69, 0xc0, 0x6c, 0x2f, 0xd3, 0x92, 0x3a, 0x0a, 0x75, 0x85, 0x15, 0xdb, 0xd8,
	0xe9, 0xec, 0x74, 0xeb, 0xab, 0x81, 0x49, 0x34, 0x8b, 0x92, 0x08, 0x0e, 0xeb, 0x25, 0x1c, 0xe8,
	0xd8, 0xdb, 0xf8, 0xaf, 0x4d, 0xc7, 0x8e, 0x3e, 0x1d, 0xd6, 0xef, 0x65, 0x40, 0x3c, 0xb0, 0xb5,
	0xc6, 0xdb, 0xaa, 0x2a, 0x67, 0x05, 0x55, 0xe9, 0xe8, 0x55, 0xc9, 0x2a, 0xcd, 0x97, 0x84, 0x7b,
	0x85, 0x49, 0x18, 0x44, 0xd2, 0xab, 0x7d, 0xac, 0x20, 0x33, 0x4a, 0x4a, 0xf5, 0x08, 0xaa, 0x13,
	0x66, 0xb3, 0x98, 0xaa, 0x15, 0x70, 0x27, 0xb3, 0x02, 0xa4, 0x6a, 0xc9, 0x80, 0x15, 0x23, 0x7a,
	0x0c, 0x75, 0x39, 0xdf, 0xf3, 0xcc, 0x3e, 0x52, 0x11, 0x0c, 0x62, 0xea, 0xfa, 0x84, 0x52, 0x31,
	0xc8, 0x3a, 0xa3, 0x15, 0xc1, 0x71, 0xce, 0xe7, 0x8d, 0xe5, 0xfd, 0x50, 0x15, 0xaf, 0x2c, 0x8a,
	0x77, 0x5c, 0xe0, 0x95, 0xac, 0x1d, 0xba, 0x0b, 0x35, 0x19, 0xd3, 0x8b, 0xc8, 0x13, 0x41, 0xd6,
	0xf0, 0x0a, 0x61, 0xfd, 0xb5, 0x03, 0x75, 0x4d, 0x66, 0xcb, 0x79, 0x6f, 0x43, 0x75, 0xb2, 0x5c,
	0xcc, 0x02, 0x4f, 0x55, 0x58, 0x41, 0xbc, 0x2f, 0x06, 0x5e, 0xe0, 0xbc, 0x16, 0xdc, 0xca, 0x98,
	0x86, 0xe1, 0x7d, 0xf1, 0x2c, 0x0a, 0x16, 0x6a, 0xdf, 0x89, 0xb3, 0xda, 0x80, 0xbb, 0xe9, 0x06,
	0x5c, 0xf5, 0x49, 0x35, 0xb3, 0x45, 0x11, 0x54, 0xbe, 0x22, 0x8b, 0xc0, 0xd8, 0x93, 0xb2, 0xfc,
	0xac, 0x15, 0x67, 0x7f, 0xdb, 0xe2, 0x88, 0x74, 0x88, 0x9c, 0x8f, 0x47, 0x46, 0x4d, 0x58, 0x58,
	0x21, 0xd6, 0x4b, 0x07, 0x5b, 0x96, 0x8e, 0xa7, 0x4d, 0xdb, 0x70, 0xe3, 0x91, 0x51, 0x17, 0x5e,
	0x66, 0x91, 0x3c, 0xb4, 0x17, 0x94, 0x44, 0xe3, 0x91, 0x71, 0x20, 0x43, 0x93, 0x10, 0xfa, 0x08,
	0x2a, 0xfc, 0x64, 0x1c, 0x8a, 0x06, 0x6e, 0x27, 0x41, 0x70, 0xdc, 0xb7, 0xe2, 0x38, 0xf6, 0xaf,
	0x02, 0x2c, 0x78, 0xd0, 0x03, 0x68, 0x60, 0xe2, 0x10, 0xf7, 0x27, 0x32, 0x57, 0x69, 0x6a, 0x08,
	0x5d, 0x6b, 0x58, 0x6b, 0x04, 0x8d, 0xac, 0xbc, 0x66, 0xbd, 0x94, 0xb1, 0x2e, 0xae, 0x27, 0xdb,
	0xfb, 0xda, 0x5e, 0x24, 0x03, 0x9b, 0xc2, 0xd6, 0x19, 0x1c, 0x5c, 0x10, 0x36, 0x89, 0xc3, 0xd0,
	0x5b, 0xf2, 0xa9, 0xe4, 0xfb, 0xd5, 0x71, 0xd2, 0x6e, 0xe4, 0xfb, 0x55, 0x82, 0x9b, 0x5a, 0xc2,
	0x7a, 0xa2, 0x6b, 0xa0, 0xa1, 0xe0, 0x13, 0x40, 0xe2, 0x85, 0x84, 0x36, 0xca, 0x7f, 0x02, 0xad,
	0x0b, 0xc2, 0x94, 0x95, 0x81, 0xed, 0xd9, 0xbe, 0x43, 0x6e, 0xf4, 0xc4, 0xea, 0x17, 0x49, 0xd0,
	0x90, 0xc7, 0xf9, 0x3c, 0xb6, 0x7d, 0xe6, 0xb2, 0xa5, 0x12, 0x49, 0xe1, 0xfe, 0xdf, 0x7b, 0x50,
	0x95, 0xa9, 0x42, 0x8f, 0xe1, 0x40, 0x7f, 0xf7, 0xa0, 0xff, 0xad, 0x7a, 0x2a, 0xf3, 0x1a, 0x32,
	0x0f, 0x93, 0xb6, 0x78, 0xba, 0x08, 0xd9, 0x12, 0x61, 0x40, 0xf9, 0x3b, 0x09, 0xbd, 0x97, 0x48,
	0x17, 0x3e, 0x76, 0xcc, 0x9b, 0xc8, 0x34, 0x44, 0x3f, 0x40, 0xbb, 0xf8, 0x72, 0x47, 0xef, 0xa7,
	0x5e, 0x6d, 0x7a, 0xbf, 0x98, 0x6f, 0x63, 0xa1, 0x21, 0xfa, 0x0e, 0x4e, 0x0a, 0x6f, 0x62, 0xd4,
	0xc9, 0xca, 0xe6, 0x1f, 0x06, 0xe6, 0x5b, 0x38, 0x68, 0x88, 0x26, 0x80, 0x9e, 0xb9, 0xfe, 0x3c,
	0x7b, 0x61, 0xad, 0x12, 0x52, 0x78, 0x69, 0x9a, 0xf7, 0x6e, 0x22, 0xd3, 0x10, 0x3d, 0x81, 0x26,
	0x7f, 0x50, 0xe8, 0xbe, 0xde, 0x4d, 0x44, 0x8a, 0x9e, 0xc6, 0xeb, 0x55, 0x1a, 0xca, 0x17, 0x74,
	0x2e, 0x9f, 0xef, 0xa4, 0x64, 0x04, 0x27, 0x9c, 0x0d, 0x13, 0xe6, 0x46, 0xb7, 0xd7, 0xf2, 0x25,
	0x34, 0xd7, 0xd6, 0x3d, 0x32, 0x37, 0xdf, 0x5d, 0xe6, 0xff, 0x37, 0xd2, 0x68, 0x88, 0xbe, 0x81,
	0x16, 0x47, 0xe7, 0xc2, 0xba, 0xb5, 0xc2, 0x4b, 0xf9, 0x5a, 0xca, 0x87, 0x78, 0x6b, 0x8d, 0x9f,
	0x41, 0x2d, 0x5d, 0x04, 0xa8, 0xa5, 0xf5, 0x7d, 0xba, 0x5d, 0xcc, 0x02, 0xac, 0x88, 0xed, 0x28,
	0x37, 0xcf, 0xab, 0x4c, 0x17, 0x2d, 0x07, 0xf3, 0x06, 0x2a, 0x0d, 0x07, 0xdd, 0x97, 0x0f, 0xae,
	0x5d, 0xe6, 0xd9, 0xb3, 0xde, 0x2c, 0xf6, 0xbc, 0x87, 0x33, 0x5e, 0x96, 0x53, 0x3b, 0xb6, 0xf9,
	0xdf, 0x43, 0xf1, 0xa1, 0xa5, 0x3e, 0xed, 0x66, 0x55, 0x01, 0x7d, 0xfa, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x90, 0x7c, 0x1f, 0x24, 0xf2, 0x0d, 0x00, 0x00,
}
