// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: event/event.proto

package event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "gitlab.bull-b.com/aua/aua-proto/rights"
import _ "gitlab.bull-b.com/aua/aua-proto/wallet"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
