// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event/event.proto

package event // import "gitlab.bull-b.com/aua/aua-proto/event"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import rights "gitlab.bull-b.com/aua/aua-proto/rights"
import wallet "gitlab.bull-b.com/aua/aua-proto/wallet"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Topic int32

const (
	Topic_System       Topic = 0
	Topic_Otc          Topic = 1
	Topic_GwUser       Topic = 2
	Topic_StateUser    Topic = 3
	Topic_SystemNotice Topic = 4
	Topic_UserUpdate   Topic = 5
	Topic_ChainNotice  Topic = 7
)

var Topic_name = map[int32]string{
	0: "System",
	1: "Otc",
	2: "GwUser",
	3: "StateUser",
	4: "SystemNotice",
	5: "UserUpdate",
	7: "ChainNotice",
}
var Topic_value = map[string]int32{
	"System":       0,
	"Otc":          1,
	"GwUser":       2,
	"StateUser":    3,
	"SystemNotice": 4,
	"UserUpdate":   5,
	"ChainNotice":  7,
}

func (x Topic) String() string {
	return proto.EnumName(Topic_name, int32(x))
}
func (Topic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{0}
}

type SystemEvent_EventType int32

const (
	SystemEvent_PermissionRequest SystemEvent_EventType = 0
	SystemEvent_PermissionUpdate  SystemEvent_EventType = 1
)

var SystemEvent_EventType_name = map[int32]string{
	0: "PermissionRequest",
	1: "PermissionUpdate",
}
var SystemEvent_EventType_value = map[string]int32{
	"PermissionRequest": 0,
	"PermissionUpdate":  1,
}

func (x SystemEvent_EventType) String() string {
	return proto.EnumName(SystemEvent_EventType_name, int32(x))
}
func (SystemEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{1, 0}
}

type GwUserEvent_EventType int32

const (
	GwUserEvent_UserLogout GwUserEvent_EventType = 0
	GwUserEvent_UserSync   GwUserEvent_EventType = 1
)

var GwUserEvent_EventType_name = map[int32]string{
	0: "UserLogout",
	1: "UserSync",
}
var GwUserEvent_EventType_value = map[string]int32{
	"UserLogout": 0,
	"UserSync":   1,
}

func (x GwUserEvent_EventType) String() string {
	return proto.EnumName(GwUserEvent_EventType_name, int32(x))
}
func (GwUserEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{2, 0}
}

type StateUserEvent_EventType int32

const (
	StateUserEvent_Duplicate       StateUserEvent_EventType = 0
	StateUserEvent_StateUserUpdate StateUserEvent_EventType = 1
)

var StateUserEvent_EventType_name = map[int32]string{
	0: "Duplicate",
	1: "StateUserUpdate",
}
var StateUserEvent_EventType_value = map[string]int32{
	"Duplicate":       0,
	"StateUserUpdate": 1,
}

func (x StateUserEvent_EventType) String() string {
	return proto.EnumName(StateUserEvent_EventType_name, int32(x))
}
func (StateUserEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{4, 0}
}

// 链上转账记录
type ChainEvent struct {
	TransferType         wallet.TransferType `protobuf:"varint,1,opt,name=TransferType,proto3,enum=wallet.TransferType" json:"TransferType,omitempty"`
	Amount               uint64              `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	ChainRecordID        uint64              `protobuf:"varint,3,opt,name=ChainRecordID,proto3" json:"ChainRecordID,omitempty"`
	RelateID             uint64              `protobuf:"varint,4,opt,name=RelateID,proto3" json:"RelateID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ChainEvent) Reset()         { *m = ChainEvent{} }
func (m *ChainEvent) String() string { return proto.CompactTextString(m) }
func (*ChainEvent) ProtoMessage()    {}
func (*ChainEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{0}
}
func (m *ChainEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainEvent.Unmarshal(m, b)
}
func (m *ChainEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainEvent.Marshal(b, m, deterministic)
}
func (dst *ChainEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainEvent.Merge(dst, src)
}
func (m *ChainEvent) XXX_Size() int {
	return xxx_messageInfo_ChainEvent.Size(m)
}
func (m *ChainEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ChainEvent proto.InternalMessageInfo

func (m *ChainEvent) GetTransferType() wallet.TransferType {
	if m != nil {
		return m.TransferType
	}
	return wallet.TransferType_TransferType_Invalid
}

func (m *ChainEvent) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChainEvent) GetChainRecordID() uint64 {
	if m != nil {
		return m.ChainRecordID
	}
	return 0
}

func (m *ChainEvent) GetRelateID() uint64 {
	if m != nil {
		return m.RelateID
	}
	return 0
}

type SystemEvent struct {
	Type SystemEvent_EventType `protobuf:"varint,1,opt,name=Type,proto3,enum=event.SystemEvent_EventType" json:"Type,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*SystemEvent_Permission
	Data                 isSystemEvent_Data `protobuf_oneof:"Data"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SystemEvent) Reset()         { *m = SystemEvent{} }
func (m *SystemEvent) String() string { return proto.CompactTextString(m) }
func (*SystemEvent) ProtoMessage()    {}
func (*SystemEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{1}
}
func (m *SystemEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemEvent.Unmarshal(m, b)
}
func (m *SystemEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemEvent.Marshal(b, m, deterministic)
}
func (dst *SystemEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemEvent.Merge(dst, src)
}
func (m *SystemEvent) XXX_Size() int {
	return xxx_messageInfo_SystemEvent.Size(m)
}
func (m *SystemEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SystemEvent proto.InternalMessageInfo

func (m *SystemEvent) GetType() SystemEvent_EventType {
	if m != nil {
		return m.Type
	}
	return SystemEvent_PermissionRequest
}

type isSystemEvent_Data interface {
	isSystemEvent_Data()
}

type SystemEvent_Permission struct {
	Permission *PermissionMap `protobuf:"bytes,2,opt,name=Permission,proto3,oneof"`
}

func (*SystemEvent_Permission) isSystemEvent_Data() {}

func (m *SystemEvent) GetData() isSystemEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SystemEvent) GetPermission() *PermissionMap {
	if x, ok := m.GetData().(*SystemEvent_Permission); ok {
		return x.Permission
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SystemEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SystemEvent_OneofMarshaler, _SystemEvent_OneofUnmarshaler, _SystemEvent_OneofSizer, []interface{}{
		(*SystemEvent_Permission)(nil),
	}
}

func _SystemEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SystemEvent)
	// Data
	switch x := m.Data.(type) {
	case *SystemEvent_Permission:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Permission); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SystemEvent.Data has unexpected type %T", x)
	}
	return nil
}

func _SystemEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SystemEvent)
	switch tag {
	case 2: // Data.Permission
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PermissionMap)
		err := b.DecodeMessage(msg)
		m.Data = &SystemEvent_Permission{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SystemEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SystemEvent)
	// Data
	switch x := m.Data.(type) {
	case *SystemEvent_Permission:
		s := proto.Size(x.Permission)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GwUserEvent struct {
	Type GwUserEvent_EventType `protobuf:"varint,1,opt,name=Type,proto3,enum=event.GwUserEvent_EventType" json:"Type,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*GwUserEvent_Logout
	//	*GwUserEvent_GWUsers
	Data                 isGwUserEvent_Data `protobuf_oneof:"Data"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GwUserEvent) Reset()         { *m = GwUserEvent{} }
func (m *GwUserEvent) String() string { return proto.CompactTextString(m) }
func (*GwUserEvent) ProtoMessage()    {}
func (*GwUserEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{2}
}
func (m *GwUserEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwUserEvent.Unmarshal(m, b)
}
func (m *GwUserEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwUserEvent.Marshal(b, m, deterministic)
}
func (dst *GwUserEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwUserEvent.Merge(dst, src)
}
func (m *GwUserEvent) XXX_Size() int {
	return xxx_messageInfo_GwUserEvent.Size(m)
}
func (m *GwUserEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GwUserEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GwUserEvent proto.InternalMessageInfo

func (m *GwUserEvent) GetType() GwUserEvent_EventType {
	if m != nil {
		return m.Type
	}
	return GwUserEvent_UserLogout
}

type isGwUserEvent_Data interface {
	isGwUserEvent_Data()
}

type GwUserEvent_Logout struct {
	Logout *LogoutMsg `protobuf:"bytes,2,opt,name=Logout,proto3,oneof"`
}

type GwUserEvent_GWUsers struct {
	GWUsers *GWUsers `protobuf:"bytes,3,opt,name=GWUsers,proto3,oneof"`
}

func (*GwUserEvent_Logout) isGwUserEvent_Data() {}

func (*GwUserEvent_GWUsers) isGwUserEvent_Data() {}

func (m *GwUserEvent) GetData() isGwUserEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GwUserEvent) GetLogout() *LogoutMsg {
	if x, ok := m.GetData().(*GwUserEvent_Logout); ok {
		return x.Logout
	}
	return nil
}

func (m *GwUserEvent) GetGWUsers() *GWUsers {
	if x, ok := m.GetData().(*GwUserEvent_GWUsers); ok {
		return x.GWUsers
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GwUserEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GwUserEvent_OneofMarshaler, _GwUserEvent_OneofUnmarshaler, _GwUserEvent_OneofSizer, []interface{}{
		(*GwUserEvent_Logout)(nil),
		(*GwUserEvent_GWUsers)(nil),
	}
}

func _GwUserEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GwUserEvent)
	// Data
	switch x := m.Data.(type) {
	case *GwUserEvent_Logout:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Logout); err != nil {
			return err
		}
	case *GwUserEvent_GWUsers:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GWUsers); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GwUserEvent.Data has unexpected type %T", x)
	}
	return nil
}

func _GwUserEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GwUserEvent)
	switch tag {
	case 2: // Data.Logout
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LogoutMsg)
		err := b.DecodeMessage(msg)
		m.Data = &GwUserEvent_Logout{msg}
		return true, err
	case 3: // Data.GWUsers
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GWUsers)
		err := b.DecodeMessage(msg)
		m.Data = &GwUserEvent_GWUsers{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GwUserEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GwUserEvent)
	// Data
	switch x := m.Data.(type) {
	case *GwUserEvent_Logout:
		s := proto.Size(x.Logout)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GwUserEvent_GWUsers:
		s := proto.Size(x.GWUsers)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GWUsers struct {
	Gateway              string     `protobuf:"bytes,1,opt,name=Gateway,proto3" json:"Gateway,omitempty"`
	Sessions             []*Session `protobuf:"bytes,2,rep,name=Sessions,proto3" json:"Sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GWUsers) Reset()         { *m = GWUsers{} }
func (m *GWUsers) String() string { return proto.CompactTextString(m) }
func (*GWUsers) ProtoMessage()    {}
func (*GWUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{3}
}
func (m *GWUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GWUsers.Unmarshal(m, b)
}
func (m *GWUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GWUsers.Marshal(b, m, deterministic)
}
func (dst *GWUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GWUsers.Merge(dst, src)
}
func (m *GWUsers) XXX_Size() int {
	return xxx_messageInfo_GWUsers.Size(m)
}
func (m *GWUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_GWUsers.DiscardUnknown(m)
}

var xxx_messageInfo_GWUsers proto.InternalMessageInfo

func (m *GWUsers) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *GWUsers) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type StateUserEvent struct {
	Type StateUserEvent_EventType `protobuf:"varint,1,opt,name=Type,proto3,enum=event.StateUserEvent_EventType" json:"Type,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*StateUserEvent_Logout
	//	*StateUserEvent_Event
	Data                 isStateUserEvent_Data `protobuf_oneof:"Data"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StateUserEvent) Reset()         { *m = StateUserEvent{} }
func (m *StateUserEvent) String() string { return proto.CompactTextString(m) }
func (*StateUserEvent) ProtoMessage()    {}
func (*StateUserEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{4}
}
func (m *StateUserEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateUserEvent.Unmarshal(m, b)
}
func (m *StateUserEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateUserEvent.Marshal(b, m, deterministic)
}
func (dst *StateUserEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateUserEvent.Merge(dst, src)
}
func (m *StateUserEvent) XXX_Size() int {
	return xxx_messageInfo_StateUserEvent.Size(m)
}
func (m *StateUserEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StateUserEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StateUserEvent proto.InternalMessageInfo

func (m *StateUserEvent) GetType() StateUserEvent_EventType {
	if m != nil {
		return m.Type
	}
	return StateUserEvent_Duplicate
}

type isStateUserEvent_Data interface {
	isStateUserEvent_Data()
}

type StateUserEvent_Logout struct {
	Logout *LogoutMsg `protobuf:"bytes,2,opt,name=Logout,proto3,oneof"`
}

type StateUserEvent_Event struct {
	Event *UserUpdateEvent `protobuf:"bytes,3,opt,name=Event,proto3,oneof"`
}

func (*StateUserEvent_Logout) isStateUserEvent_Data() {}

func (*StateUserEvent_Event) isStateUserEvent_Data() {}

func (m *StateUserEvent) GetData() isStateUserEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StateUserEvent) GetLogout() *LogoutMsg {
	if x, ok := m.GetData().(*StateUserEvent_Logout); ok {
		return x.Logout
	}
	return nil
}

func (m *StateUserEvent) GetEvent() *UserUpdateEvent {
	if x, ok := m.GetData().(*StateUserEvent_Event); ok {
		return x.Event
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StateUserEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StateUserEvent_OneofMarshaler, _StateUserEvent_OneofUnmarshaler, _StateUserEvent_OneofSizer, []interface{}{
		(*StateUserEvent_Logout)(nil),
		(*StateUserEvent_Event)(nil),
	}
}

func _StateUserEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StateUserEvent)
	// Data
	switch x := m.Data.(type) {
	case *StateUserEvent_Logout:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Logout); err != nil {
			return err
		}
	case *StateUserEvent_Event:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Event); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StateUserEvent.Data has unexpected type %T", x)
	}
	return nil
}

func _StateUserEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StateUserEvent)
	switch tag {
	case 2: // Data.Logout
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LogoutMsg)
		err := b.DecodeMessage(msg)
		m.Data = &StateUserEvent_Logout{msg}
		return true, err
	case 3: // Data.Event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserUpdateEvent)
		err := b.DecodeMessage(msg)
		m.Data = &StateUserEvent_Event{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StateUserEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StateUserEvent)
	// Data
	switch x := m.Data.(type) {
	case *StateUserEvent_Logout:
		s := proto.Size(x.Logout)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StateUserEvent_Event:
		s := proto.Size(x.Event)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SystemNoticeEvent struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemNoticeEvent) Reset()         { *m = SystemNoticeEvent{} }
func (m *SystemNoticeEvent) String() string { return proto.CompactTextString(m) }
func (*SystemNoticeEvent) ProtoMessage()    {}
func (*SystemNoticeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{5}
}
func (m *SystemNoticeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemNoticeEvent.Unmarshal(m, b)
}
func (m *SystemNoticeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemNoticeEvent.Marshal(b, m, deterministic)
}
func (dst *SystemNoticeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemNoticeEvent.Merge(dst, src)
}
func (m *SystemNoticeEvent) XXX_Size() int {
	return xxx_messageInfo_SystemNoticeEvent.Size(m)
}
func (m *SystemNoticeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemNoticeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SystemNoticeEvent proto.InternalMessageInfo

type UserUpdateEvent struct {
	UserID               uint64          `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Kick                 bool            `protobuf:"varint,2,opt,name=Kick,proto3" json:"Kick,omitempty"`
	UserName             string          `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	MobilePrefix         string          `protobuf:"bytes,4,opt,name=MobilePrefix,proto3" json:"MobilePrefix,omitempty"`
	Mobile               string          `protobuf:"bytes,5,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Email                string          `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`
	UserType             uint32          `protobuf:"varint,7,opt,name=UserType,proto3" json:"UserType,omitempty"`
	Rights               []rights.Rights `protobuf:"varint,8,rep,packed,name=Rights,proto3,enum=rights.Rights" json:"Rights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserUpdateEvent) Reset()         { *m = UserUpdateEvent{} }
func (m *UserUpdateEvent) String() string { return proto.CompactTextString(m) }
func (*UserUpdateEvent) ProtoMessage()    {}
func (*UserUpdateEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{6}
}
func (m *UserUpdateEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateEvent.Unmarshal(m, b)
}
func (m *UserUpdateEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateEvent.Marshal(b, m, deterministic)
}
func (dst *UserUpdateEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateEvent.Merge(dst, src)
}
func (m *UserUpdateEvent) XXX_Size() int {
	return xxx_messageInfo_UserUpdateEvent.Size(m)
}
func (m *UserUpdateEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateEvent proto.InternalMessageInfo

func (m *UserUpdateEvent) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserUpdateEvent) GetKick() bool {
	if m != nil {
		return m.Kick
	}
	return false
}

func (m *UserUpdateEvent) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserUpdateEvent) GetMobilePrefix() string {
	if m != nil {
		return m.MobilePrefix
	}
	return ""
}

func (m *UserUpdateEvent) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserUpdateEvent) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserUpdateEvent) GetUserType() uint32 {
	if m != nil {
		return m.UserType
	}
	return 0
}

func (m *UserUpdateEvent) GetRights() []rights.Rights {
	if m != nil {
		return m.Rights
	}
	return nil
}

type MapFieldEntry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapFieldEntry) Reset()         { *m = MapFieldEntry{} }
func (m *MapFieldEntry) String() string { return proto.CompactTextString(m) }
func (*MapFieldEntry) ProtoMessage()    {}
func (*MapFieldEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{7}
}
func (m *MapFieldEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapFieldEntry.Unmarshal(m, b)
}
func (m *MapFieldEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapFieldEntry.Marshal(b, m, deterministic)
}
func (dst *MapFieldEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapFieldEntry.Merge(dst, src)
}
func (m *MapFieldEntry) XXX_Size() int {
	return xxx_messageInfo_MapFieldEntry.Size(m)
}
func (m *MapFieldEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MapFieldEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MapFieldEntry proto.InternalMessageInfo

func (m *MapFieldEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MapFieldEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PermissionMap struct {
	Entry                []*MapFieldEntry `protobuf:"bytes,1,rep,name=Entry,proto3" json:"Entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PermissionMap) Reset()         { *m = PermissionMap{} }
func (m *PermissionMap) String() string { return proto.CompactTextString(m) }
func (*PermissionMap) ProtoMessage()    {}
func (*PermissionMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{8}
}
func (m *PermissionMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionMap.Unmarshal(m, b)
}
func (m *PermissionMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionMap.Marshal(b, m, deterministic)
}
func (dst *PermissionMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionMap.Merge(dst, src)
}
func (m *PermissionMap) XXX_Size() int {
	return xxx_messageInfo_PermissionMap.Size(m)
}
func (m *PermissionMap) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionMap.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionMap proto.InternalMessageInfo

func (m *PermissionMap) GetEntry() []*MapFieldEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type LogoutMsg struct {
	UserID               uint64     `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CookieID             string     `protobuf:"bytes,2,opt,name=CookieID,proto3" json:"CookieID,omitempty"`
	SessionID            string     `protobuf:"bytes,3,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Gateway              string     `protobuf:"bytes,4,opt,name=Gateway,proto3" json:"Gateway,omitempty"`
	Type                 LogoutType `protobuf:"varint,5,opt,name=Type,proto3,enum=event.LogoutType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LogoutMsg) Reset()         { *m = LogoutMsg{} }
func (m *LogoutMsg) String() string { return proto.CompactTextString(m) }
func (*LogoutMsg) ProtoMessage()    {}
func (*LogoutMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_09501de94aff108a, []int{9}
}
func (m *LogoutMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutMsg.Unmarshal(m, b)
}
func (m *LogoutMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutMsg.Marshal(b, m, deterministic)
}
func (dst *LogoutMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutMsg.Merge(dst, src)
}
func (m *LogoutMsg) XXX_Size() int {
	return xxx_messageInfo_LogoutMsg.Size(m)
}
func (m *LogoutMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutMsg proto.InternalMessageInfo

func (m *LogoutMsg) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *LogoutMsg) GetCookieID() string {
	if m != nil {
		return m.CookieID
	}
	return ""
}

func (m *LogoutMsg) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *LogoutMsg) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *LogoutMsg) GetType() LogoutType {
	if m != nil {
		return m.Type
	}
	return LogoutType_Disconnect
}

func init() {
	proto.RegisterType((*ChainEvent)(nil), "event.ChainEvent")
	proto.RegisterType((*SystemEvent)(nil), "event.SystemEvent")
	proto.RegisterType((*GwUserEvent)(nil), "event.GwUserEvent")
	proto.RegisterType((*GWUsers)(nil), "event.GWUsers")
	proto.RegisterType((*StateUserEvent)(nil), "event.StateUserEvent")
	proto.RegisterType((*SystemNoticeEvent)(nil), "event.SystemNoticeEvent")
	proto.RegisterType((*UserUpdateEvent)(nil), "event.UserUpdateEvent")
	proto.RegisterType((*MapFieldEntry)(nil), "event.MapFieldEntry")
	proto.RegisterType((*PermissionMap)(nil), "event.PermissionMap")
	proto.RegisterType((*LogoutMsg)(nil), "event.LogoutMsg")
	proto.RegisterEnum("event.Topic", Topic_name, Topic_value)
	proto.RegisterEnum("event.SystemEvent_EventType", SystemEvent_EventType_name, SystemEvent_EventType_value)
	proto.RegisterEnum("event.GwUserEvent_EventType", GwUserEvent_EventType_name, GwUserEvent_EventType_value)
	proto.RegisterEnum("event.StateUserEvent_EventType", StateUserEvent_EventType_name, StateUserEvent_EventType_value)
}

func init() { proto.RegisterFile("event/event.proto", fileDescriptor_event_09501de94aff108a) }

var fileDescriptor_event_09501de94aff108a = []byte{
	// 786 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6e, 0xeb, 0x44,
	0x14, 0xb6, 0x1b, 0x3b, 0x89, 0x4f, 0x7e, 0xea, 0x4c, 0xc3, 0x95, 0x15, 0x5d, 0x89, 0xc8, 0xe2,
	0x42, 0x88, 0x74, 0x1d, 0x94, 0x2b, 0x41, 0x25, 0x9e, 0x68, 0x53, 0x9a, 0xaa, 0xa4, 0xad, 0x26,
	0x2d, 0x48, 0xbc, 0x4d, 0xdc, 0x69, 0x6a, 0xea, 0xd8, 0xc1, 0x1e, 0xb7, 0x64, 0x33, 0x88, 0x6d,
	0xb0, 0x05, 0x96, 0xc0, 0x26, 0xd8, 0x02, 0x9a, 0x1f, 0x3b, 0x36, 0x15, 0xbc, 0xf0, 0x10, 0xc7,
	0xdf, 0x77, 0xbe, 0x39, 0x73, 0xe6, 0xcc, 0x37, 0x63, 0xe8, 0xd1, 0x67, 0x1a, 0xb1, 0x89, 0x78,
	0x7a, 0xdb, 0x24, 0x66, 0x31, 0x32, 0x05, 0x18, 0xd8, 0x2a, 0x12, 0x65, 0x1b, 0x19, 0x18, 0xf4,
	0x25, 0x93, 0xd2, 0xe4, 0x39, 0xf0, 0x69, 0xaa, 0xd8, 0xa3, 0x24, 0x58, 0x3f, 0xb2, 0x74, 0x22,
	0xff, 0x14, 0xd9, 0x7b, 0x21, 0x61, 0x48, 0xcb, 0xa3, 0xdd, 0xdf, 0x74, 0x80, 0xd3, 0x47, 0x12,
	0x44, 0x67, 0x3c, 0x0b, 0x3a, 0x86, 0xf6, 0x6d, 0x42, 0xa2, 0xf4, 0x81, 0x26, 0xb7, 0xbb, 0x2d,
	0x75, 0xf4, 0xa1, 0x3e, 0xea, 0x4e, 0xfb, 0x9e, 0x1c, 0xe8, 0x95, 0x63, 0xb8, 0xa2, 0x44, 0x6f,
	0xa0, 0xfe, 0xcd, 0x26, 0xce, 0x22, 0xe6, 0x1c, 0x0c, 0xf5, 0x91, 0x81, 0x15, 0x42, 0x9f, 0x40,
	0x47, 0xe4, 0xc7, 0xd4, 0x8f, 0x93, 0xfb, 0x8b, 0x99, 0x53, 0x13, 0xe1, 0x2a, 0x89, 0x06, 0xd0,
	0xc4, 0x34, 0x24, 0x8c, 0x5e, 0xcc, 0x1c, 0x43, 0x08, 0x0a, 0xec, 0xfe, 0xae, 0x43, 0x6b, 0xb9,
	0x4b, 0x19, 0xdd, 0xc8, 0x1a, 0xbf, 0x00, 0xa3, 0x54, 0xdb, 0x5b, 0x4f, 0x76, 0xa9, 0xa4, 0xf0,
	0xc4, 0x53, 0xd4, 0x28, 0x94, 0xe8, 0x4b, 0x80, 0x1b, 0x9a, 0x6c, 0x82, 0x34, 0x0d, 0xe2, 0x48,
	0xd4, 0xd7, 0x9a, 0xf6, 0xd5, 0xb8, 0x7d, 0x60, 0x41, 0xb6, 0x73, 0x0d, 0x97, 0x94, 0xee, 0x31,
	0x58, 0x45, 0x2a, 0xf4, 0x11, 0xf4, 0xf6, 0x21, 0x4c, 0x7f, 0xce, 0x68, 0xca, 0x6c, 0x0d, 0xf5,
	0xc1, 0xde, 0xd3, 0x77, 0xdb, 0x7b, 0xc2, 0xa8, 0xad, 0x9f, 0xd4, 0xc1, 0x98, 0x11, 0x46, 0xdc,
	0x3f, 0x74, 0x68, 0x9d, 0xbf, 0xdc, 0xa5, 0x34, 0xf9, 0xaf, 0xda, 0x4b, 0x8a, 0x57, 0xb5, 0x8f,
	0xa1, 0xfe, 0x5d, 0xbc, 0x8e, 0x33, 0xa6, 0xea, 0xb6, 0xd5, 0x18, 0x49, 0x2e, 0xd2, 0xf5, 0x5c,
	0xc3, 0x4a, 0x81, 0xc6, 0xd0, 0x38, 0xff, 0x81, 0xa7, 0x4a, 0x45, 0x97, 0x5b, 0xd3, 0x6e, 0x3e,
	0x81, 0x64, 0xe7, 0x1a, 0xce, 0x05, 0xee, 0xe7, 0xe5, 0xb5, 0x75, 0x01, 0x38, 0x2b, 0xd3, 0xd8,
	0x1a, 0x6a, 0x43, 0x93, 0xe3, 0xe5, 0x2e, 0xf2, 0x4b, 0x8b, 0xb9, 0x2e, 0xd2, 0x23, 0x07, 0x1a,
	0xe7, 0x84, 0xd1, 0x17, 0xb2, 0x13, 0x4b, 0xb1, 0x70, 0x0e, 0xd1, 0x18, 0x9a, 0x4b, 0x2a, 0x9a,
	0x91, 0x3a, 0x07, 0xc3, 0x5a, 0xa9, 0x08, 0x45, 0xe3, 0x22, 0xee, 0xfe, 0xa9, 0x43, 0x77, 0xc9,
	0x08, 0xa3, 0xfb, 0x06, 0x7d, 0xa8, 0x34, 0xe8, 0xe3, 0x7c, 0x68, 0x45, 0xf4, 0xbf, 0x7a, 0xe4,
	0x81, 0x29, 0x86, 0xab, 0x0e, 0xbd, 0x51, 0x52, 0x9e, 0x5c, 0xee, 0x9e, 0x88, 0xce, 0x35, 0x2c,
	0x65, 0xee, 0xa4, 0xdc, 0xa7, 0x0e, 0x58, 0xb3, 0x6c, 0x1b, 0x06, 0x3e, 0xdf, 0x65, 0x0d, 0x1d,
	0xc1, 0x61, 0x51, 0xd9, 0xab, 0xad, 0x3f, 0x82, 0x9e, 0xf4, 0xe4, 0x55, 0xcc, 0x02, 0x5f, 0xa6,
	0x75, 0xff, 0xd2, 0xe1, 0xf0, 0x1f, 0x53, 0xf1, 0x93, 0xc3, 0xa9, 0x8b, 0x99, 0x58, 0xb4, 0x81,
	0x15, 0x42, 0x08, 0x8c, 0xcb, 0xc0, 0x7f, 0x12, 0x6b, 0x6a, 0x62, 0xf1, 0xce, 0xcf, 0x09, 0x8f,
	0x5e, 0x91, 0x0d, 0x15, 0x0b, 0xb0, 0x70, 0x81, 0x91, 0x0b, 0xed, 0x45, 0xbc, 0x0a, 0x42, 0x7a,
	0x93, 0xd0, 0x87, 0xe0, 0x17, 0x71, 0x8e, 0x2c, 0x5c, 0xe1, 0xf8, 0x5c, 0x12, 0x3b, 0xa6, 0x88,
	0x2a, 0x84, 0xfa, 0x60, 0x9e, 0x6d, 0x48, 0x10, 0x3a, 0x75, 0x41, 0x4b, 0x90, 0xcf, 0x26, 0x36,
	0xa4, 0x31, 0xd4, 0x47, 0x1d, 0x5c, 0x60, 0xf4, 0x29, 0xd4, 0xb1, 0xb8, 0x5b, 0x9c, 0xe6, 0xb0,
	0x36, 0xea, 0x4e, 0xbb, 0x9e, 0xba, 0x6a, 0x24, 0x8b, 0x55, 0xd4, 0xfd, 0x0a, 0x3a, 0x0b, 0xb2,
	0xfd, 0x36, 0xa0, 0xe1, 0xfd, 0x59, 0xc4, 0x92, 0x1d, 0xb2, 0xa1, 0x76, 0x49, 0x73, 0xdb, 0xf0,
	0x57, 0x3e, 0xf9, 0xf7, 0x24, 0xcc, 0xa8, 0x58, 0xa9, 0x85, 0x25, 0x70, 0xbf, 0x86, 0x4e, 0xe5,
	0x6c, 0xa2, 0x31, 0x98, 0x22, 0x83, 0xa3, 0x0b, 0x5b, 0xe5, 0x07, 0xb8, 0x92, 0x1d, 0x4b, 0x89,
	0xfb, 0xab, 0x0e, 0x56, 0xb1, 0xfb, 0xff, 0xda, 0xe1, 0x01, 0x34, 0x4f, 0xe3, 0xf8, 0x29, 0xe0,
	0xb7, 0x8e, 0x9c, 0xbb, 0xc0, 0xe8, 0x2d, 0x58, 0xca, 0xa7, 0xea, 0xce, 0xb2, 0xf0, 0x9e, 0x28,
	0xfb, 0xdf, 0xa8, 0xfa, 0xff, 0x9d, 0x32, 0xb0, 0x29, 0x0c, 0xdc, 0xab, 0x38, 0x71, 0x6f, 0xd9,
	0xf1, 0x4f, 0x60, 0xde, 0xc6, 0xdb, 0xc0, 0x47, 0x00, 0x75, 0x69, 0x13, 0x5b, 0x43, 0x0d, 0xa8,
	0x5d, 0x33, 0xdf, 0xd6, 0x39, 0x29, 0xef, 0x04, 0xfb, 0x80, 0x7b, 0xae, 0x30, 0x99, 0x5d, 0x43,
	0x36, 0xb4, 0xcb, 0xb6, 0xb2, 0x8d, 0xfc, 0xf0, 0x2a, 0x03, 0x9a, 0xe8, 0x10, 0x5a, 0xe2, 0x72,
	0x55, 0x82, 0xc6, 0xc9, 0x67, 0x3f, 0xbe, 0x5b, 0x07, 0x2c, 0x24, 0x2b, 0x6f, 0x95, 0x85, 0xe1,
	0xfb, 0x95, 0xe7, 0xc7, 0x9b, 0x09, 0xc9, 0x08, 0xff, 0xbd, 0x17, 0x9f, 0x01, 0xf9, 0xa5, 0x59,
	0xd5, 0x05, 0xf8, 0xf0, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x31, 0xbe, 0x09, 0x7f, 0x06,
	0x00, 0x00,
}
