// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event/services.proto

package event // import "gitlab.bull-b.com/aua/aua-proto/event"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "gitlab.bull-b.com/aua/aua-proto/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginReq struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CookieID             string   `protobuf:"bytes,2,opt,name=CookieID,proto3" json:"CookieID,omitempty"`
	SessionID            string   `protobuf:"bytes,3,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Gateway              string   `protobuf:"bytes,4,opt,name=Gateway,proto3" json:"Gateway,omitempty"`
	SessionUser          string   `protobuf:"bytes,5,opt,name=SessionUser,proto3" json:"SessionUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_8b3e69f133d005d7, []int{0}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *LoginReq) GetCookieID() string {
	if m != nil {
		return m.CookieID
	}
	return ""
}

func (m *LoginReq) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *LoginReq) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *LoginReq) GetSessionUser() string {
	if m != nil {
		return m.SessionUser
	}
	return ""
}

type Session struct {
	CookieID             string   `protobuf:"bytes,1,opt,name=CookieID,proto3" json:"CookieID,omitempty"`
	SessionID            string   `protobuf:"bytes,2,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Gateway              string   `protobuf:"bytes,3,opt,name=Gateway,proto3" json:"Gateway,omitempty"`
	UserID               uint64   `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_8b3e69f133d005d7, []int{1}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetCookieID() string {
	if m != nil {
		return m.CookieID
	}
	return ""
}

func (m *Session) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Session) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *Session) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GWInfo struct {
	Gateway              string   `protobuf:"bytes,1,opt,name=Gateway,proto3" json:"Gateway,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GWInfo) Reset()         { *m = GWInfo{} }
func (m *GWInfo) String() string { return proto.CompactTextString(m) }
func (*GWInfo) ProtoMessage()    {}
func (*GWInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_8b3e69f133d005d7, []int{2}
}
func (m *GWInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GWInfo.Unmarshal(m, b)
}
func (m *GWInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GWInfo.Marshal(b, m, deterministic)
}
func (dst *GWInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GWInfo.Merge(dst, src)
}
func (m *GWInfo) XXX_Size() int {
	return xxx_messageInfo_GWInfo.Size(m)
}
func (m *GWInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GWInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GWInfo proto.InternalMessageInfo

func (m *GWInfo) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

type ConnectRsp struct {
	SessionUser          string   `protobuf:"bytes,1,opt,name=SessionUser,proto3" json:"SessionUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRsp) Reset()         { *m = ConnectRsp{} }
func (m *ConnectRsp) String() string { return proto.CompactTextString(m) }
func (*ConnectRsp) ProtoMessage()    {}
func (*ConnectRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_8b3e69f133d005d7, []int{3}
}
func (m *ConnectRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRsp.Unmarshal(m, b)
}
func (m *ConnectRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRsp.Marshal(b, m, deterministic)
}
func (dst *ConnectRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRsp.Merge(dst, src)
}
func (m *ConnectRsp) XXX_Size() int {
	return xxx_messageInfo_ConnectRsp.Size(m)
}
func (m *ConnectRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRsp proto.InternalMessageInfo

func (m *ConnectRsp) GetSessionUser() string {
	if m != nil {
		return m.SessionUser
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "event.LoginReq")
	proto.RegisterType((*Session)(nil), "event.Session")
	proto.RegisterType((*GWInfo)(nil), "event.GWInfo")
	proto.RegisterType((*ConnectRsp)(nil), "event.ConnectRsp")
}

func init() { proto.RegisterFile("event/services.proto", fileDescriptor_services_8b3e69f133d005d7) }

var fileDescriptor_services_8b3e69f133d005d7 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xdf, 0x6a, 0xfa, 0x30,
	0x14, 0x36, 0x6a, 0xad, 0x9e, 0x1f, 0xfe, 0xc6, 0xb2, 0x31, 0x4a, 0xd9, 0x85, 0x04, 0xc6, 0x14,
	0x66, 0x0a, 0xdb, 0x1b, 0x4c, 0x47, 0x29, 0xec, 0xaa, 0x65, 0x08, 0xbb, 0x4b, 0x5d, 0xe6, 0xca,
	0x34, 0x71, 0x4d, 0xaa, 0xf8, 0x26, 0x7b, 0x97, 0xbd, 0xdc, 0x30, 0xc6, 0x69, 0x27, 0xb8, 0x8b,
	0x52, 0xbe, 0xf3, 0x9d, 0x3f, 0xdf, 0x77, 0x4e, 0xe0, 0x9c, 0x2f, 0xb8, 0xd0, 0x81, 0xe2, 0xf9,
	0x22, 0x1b, 0x73, 0x45, 0xe7, 0xb9, 0xd4, 0x12, 0x3b, 0x26, 0xea, 0x9f, 0x8d, 0xe5, 0x6c, 0x26,
	0x45, 0xb0, 0xf9, 0x6d, 0x38, 0xf2, 0x89, 0xa0, 0xf9, 0x28, 0x27, 0x99, 0x88, 0xf9, 0x07, 0xbe,
	0x80, 0xc6, 0x93, 0xe2, 0x79, 0x34, 0xf4, 0x50, 0x07, 0x75, 0xeb, 0xb1, 0x45, 0xd8, 0x87, 0xe6,
	0x40, 0xca, 0xf7, 0x8c, 0x47, 0x43, 0xaf, 0xda, 0x41, 0xdd, 0x56, 0xfc, 0x83, 0xf1, 0x25, 0xb4,
	0x12, 0xae, 0x54, 0x26, 0x45, 0x34, 0xf4, 0x6a, 0x86, 0xdc, 0x05, 0xb0, 0x07, 0x6e, 0xc8, 0x34,
	0x5f, 0xb2, 0x95, 0x57, 0x37, 0xdc, 0x16, 0xe2, 0x0e, 0xfc, 0xb3, 0x69, 0xeb, 0x21, 0x9e, 0x63,
	0xd8, 0xfd, 0x10, 0x29, 0xc0, 0xb5, 0xb0, 0x24, 0x00, 0x1d, 0x13, 0x50, 0x3d, 0x22, 0xa0, 0x56,
	0x16, 0xb0, 0x33, 0x5b, 0xdf, 0x37, 0x4b, 0x08, 0x34, 0xc2, 0x51, 0x24, 0x5e, 0xe5, 0x7e, 0x2d,
	0x2a, 0xd5, 0x12, 0x0a, 0x30, 0x90, 0x42, 0xf0, 0xb1, 0x8e, 0xd5, 0xfc, 0xb7, 0x15, 0x74, 0x60,
	0xe5, 0xf6, 0x0b, 0x81, 0x93, 0x68, 0xa6, 0x39, 0xee, 0x81, 0x63, 0xd6, 0x8d, 0x4f, 0xa8, 0xb9,
	0x0a, 0xdd, 0x2e, 0xdf, 0x6f, 0x53, 0x7b, 0x98, 0x87, 0xd9, 0x5c, 0xaf, 0x48, 0x05, 0x53, 0x70,
	0xed, 0x10, 0xfc, 0xdf, 0x26, 0xdb, 0x9e, 0xfe, 0xa9, 0xc5, 0x3b, 0x11, 0xa4, 0x82, 0x7b, 0xe0,
	0x86, 0xa3, 0x44, 0xb3, 0x5c, 0xe3, 0xb6, 0xe5, 0x37, 0x46, 0x0e, 0x5b, 0xdf, 0x00, 0x84, 0xa3,
	0xe4, 0xad, 0xd0, 0x2f, 0x72, 0x29, 0xfe, 0xca, 0xbe, 0xbf, 0x7e, 0xbe, 0x9a, 0x64, 0x7a, 0xca,
	0x52, 0x9a, 0x16, 0xd3, 0x69, 0x3f, 0x5d, 0xf3, 0x01, 0x2b, 0xd8, 0xfa, 0xeb, 0x9b, 0x67, 0x14,
	0x98, 0x06, 0x69, 0xc3, 0x80, 0xbb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x7f, 0x71, 0xe9,
	0x87, 0x02, 0x00, 0x00,
}
