// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common // import "gitlab.bull-b.com/aua/aua-proto/common"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PageReq struct {
	PageIndex            int64    `protobuf:"varint,1,opt,name=PageIndex,proto3" json:"PageIndex,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageReq) Reset()         { *m = PageReq{} }
func (m *PageReq) String() string { return proto.CompactTextString(m) }
func (*PageReq) ProtoMessage()    {}
func (*PageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_b035fd7f3f22d88a, []int{0}
}
func (m *PageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageReq.Unmarshal(m, b)
}
func (m *PageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageReq.Marshal(b, m, deterministic)
}
func (dst *PageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageReq.Merge(dst, src)
}
func (m *PageReq) XXX_Size() int {
	return xxx_messageInfo_PageReq.Size(m)
}
func (m *PageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PageReq.DiscardUnknown(m)
}

var xxx_messageInfo_PageReq proto.InternalMessageInfo

func (m *PageReq) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *PageReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type RespBody struct {
	Ret                  bool     `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespBody) Reset()         { *m = RespBody{} }
func (m *RespBody) String() string { return proto.CompactTextString(m) }
func (*RespBody) ProtoMessage()    {}
func (*RespBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_b035fd7f3f22d88a, []int{1}
}
func (m *RespBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespBody.Unmarshal(m, b)
}
func (m *RespBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespBody.Marshal(b, m, deterministic)
}
func (dst *RespBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespBody.Merge(dst, src)
}
func (m *RespBody) XXX_Size() int {
	return xxx_messageInfo_RespBody.Size(m)
}
func (m *RespBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RespBody.DiscardUnknown(m)
}

var xxx_messageInfo_RespBody proto.InternalMessageInfo

func (m *RespBody) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

func (m *RespBody) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespBody) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RespBody) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_b035fd7f3f22d88a, []int{2}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type IDs struct {
	IDs                  []uint64 `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDs) Reset()         { *m = IDs{} }
func (m *IDs) String() string { return proto.CompactTextString(m) }
func (*IDs) ProtoMessage()    {}
func (*IDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_b035fd7f3f22d88a, []int{3}
}
func (m *IDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDs.Unmarshal(m, b)
}
func (m *IDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDs.Marshal(b, m, deterministic)
}
func (dst *IDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDs.Merge(dst, src)
}
func (m *IDs) XXX_Size() int {
	return xxx_messageInfo_IDs.Size(m)
}
func (m *IDs) XXX_DiscardUnknown() {
	xxx_messageInfo_IDs.DiscardUnknown(m)
}

var xxx_messageInfo_IDs proto.InternalMessageInfo

func (m *IDs) GetIDs() []uint64 {
	if m != nil {
		return m.IDs
	}
	return nil
}

func init() {
	proto.RegisterType((*PageReq)(nil), "common.PageReq")
	proto.RegisterType((*RespBody)(nil), "common.RespBody")
	proto.RegisterType((*Empty)(nil), "common.Empty")
	proto.RegisterType((*IDs)(nil), "common.IDs")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_common_b035fd7f3f22d88a) }

var fileDescriptor_common_b035fd7f3f22d88a = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x86, 0x71, 0x65, 0x27, 0xce, 0x4d, 0x45, 0x2d, 0x54, 0x94, 0x0e, 0x46, 0x43, 0xd1, 0x12,
	0x67, 0xe8, 0x1b, 0x24, 0xce, 0xe0, 0xad, 0x5c, 0xb7, 0x6c, 0x52, 0x2c, 0x42, 0xc0, 0xca, 0xb9,
	0xb2, 0x02, 0x4d, 0x9f, 0xbe, 0x48, 0x2a, 0xed, 0x20, 0xf4, 0x7d, 0x27, 0xfd, 0x07, 0x3f, 0x3c,
	0x1c, 0xc9, 0x39, 0xba, 0x6c, 0xf2, 0xd5, 0x4e, 0x9e, 0x02, 0xf1, 0x45, 0x36, 0xb9, 0x83, 0xe5,
	0xbb, 0x3e, 0x59, 0xb4, 0x9f, 0xfc, 0x05, 0x56, 0x11, 0xfb, 0xcb, 0x60, 0xbf, 0x44, 0xd1, 0x14,
	0x8a, 0xe1, 0xff, 0x80, 0x3f, 0x43, 0x1d, 0xe5, 0xe3, 0xfc, 0x6d, 0xc5, 0x5d, 0x7a, 0xfc, 0x73,
	0x79, 0x80, 0x1a, 0xed, 0x3c, 0x6d, 0x69, 0xb8, 0xf1, 0x7b, 0x60, 0x68, 0x43, 0xca, 0xd7, 0x18,
	0x91, 0x73, 0x28, 0x77, 0x34, 0xe4, 0x54, 0x85, 0x89, 0xf9, 0x23, 0x54, 0x7b, 0xef, 0xc9, 0x0b,
	0xd6, 0x14, 0x6a, 0x85, 0x59, 0xe2, 0xcf, 0x4e, 0x07, 0x2d, 0xca, 0x34, 0x4c, 0x2c, 0x97, 0x50,
	0xed, 0xdd, 0x14, 0x6e, 0xf2, 0x09, 0x58, 0xdf, 0xcd, 0x71, 0x7f, 0xdf, 0xcd, 0xa2, 0x68, 0x98,
	0x2a, 0x31, 0xe2, 0x56, 0x1d, 0x5e, 0x4f, 0xe7, 0x30, 0x6a, 0xd3, 0x9a, 0xeb, 0x38, 0xae, 0x4d,
	0x7b, 0x24, 0xb7, 0xd1, 0x57, 0x1d, 0xcf, 0x3a, 0xb5, 0xfd, 0xad, 0x6e, 0x16, 0xc9, 0xde, 0x7e,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xd7, 0x30, 0x02, 0x12, 0x01, 0x00, 0x00,
}
