// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user/enum.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user/enum.proto
	user/user.proto

It has these top-level messages:
	SendEmailReq
	RoleReq
	RoleRsp
	RoleInfo
	BindReceiptAddressReq
	ReceiptAddress
	LoginReq
	LoginRsp
	RegistReq
	RegisterRsp
	GetUserInfoReq
	GetUserRightRsp
	UserInfo
	UserBrief
	GetRecaptchaKeyRsp
	SendVerifyCodeReq
	SendVerifyCodeRsp
	CheckVerifyCodeReq
	ResetPasswordReq
	ChangePasswordReq
	SetTradePasswordReq
	ChangeTradePasswordReq
	ChangeMobileReq
	BindMobileReq
	ChangeEmailReq
	BindEmailReq
	SetReceiveAddressReq
	ChangeNickNameReq
	ChangeIconReq
	UserAttachment
	Identify
	GetIdentifyRsp
	PageIdentifyReq
	PageIdentifyRsp
	IdentifyReq
	UpdateIdentifyRemarkReq
	UserBank
	UpdateIdentifyReq
	CheckUserReq
	PageUserReq
	PageUserRsp
	UserReportReq
	UserReportRsp
	PageMerchantReq
	PageMerchantRsp
	Merchant
	ChangeUserStatusReq
	ChangeUserTypeReq
	ChangeUserRoleReq
	CreateUserReq
	CreateRoleReq
	RightsInRole
	UpdateRoleReq
	UpdateUserBriefReq
	UpdateUserPasswordReq
	UpdateUserTradePasswordReq
	CountryCode
	GetCountryCodeRsp
	VerifyCode
	PageVerifyCodeReq
	PageVerifyCodeRsp
	TwiceAuthSecret
	TwiceAuthOpenReq
	TwiceAuthCloseReq
	UpdateIdentifyDocumentsReq
	AddBanksReq
	IdentifyRealIDReq
	IdentifyRealIDRsp
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
